#!/usr/bin/env python3
"""Regenerate mlsys/sw.js: the ML Systems course as an installable offline app.

Run after adding or renaming course files:  python3 dev/build-mlsys-sw.py
Network-first (you always get the latest online), cache fallback offline.
Precaches every page, asset, shared font and lab source; skips media/ (the MP4 is 30+ MB).
The cache name is a hash of the file list and contents, so any change ships a new cache.
"""
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COURSE = ROOT / "mlsys"

files = ["./"]
files += sorted(p.relative_to(COURSE).as_posix() for p in COURSE.glob("*.html"))
files += ["manifest.webmanifest"]
files += sorted(p.relative_to(COURSE).as_posix() for p in (COURSE / "assets").iterdir() if p.is_file())
files += sorted(p.relative_to(COURSE).as_posix() for p in (COURSE / "labs").rglob("*")
                if p.is_file() and p.suffix in {".cu", ".h", ".md"} or p.name == "Makefile")
files += ["../assets/course-figures.css", "../assets/fonts.css"]
files += sorted("../assets/fonts/" + p.name for p in (ROOT / "assets/fonts").glob("*.woff2"))

h = hashlib.sha1()
for f in files:
    path = (COURSE / f).resolve() if f != "./" else COURSE / "index.html"
    h.update(f.encode())
    if path.is_file():
        h.update(path.read_bytes())
version = h.hexdigest()[:10]

sw = f"""/* ML Systems course PWA, generated by dev/build-mlsys-sw.py. Do not edit by hand.
   Network-first for course files (always fresh online), cache fallback offline. */
'use strict';
const CACHE = 'mlsys-{version}';
const FILES = {files!r};
self.addEventListener('install', event => {{
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES)).then(() => self.skipWaiting()));
}});
self.addEventListener('activate', event => {{
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('mlsys-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
}});
self.addEventListener('fetch', event => {{
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  const course = new URL('./', self.location).pathname;
  const shared = [new URL('../assets/fonts', self.location).pathname, new URL('../assets/course-figures.css', self.location).pathname];
  if (!url.pathname.startsWith(course) && !shared.some(p => url.pathname.startsWith(p))) return;
  if (url.pathname.startsWith(course + 'media/')) return;   // big video: straight to the network
  event.respondWith(fetch(request).then(response => {{
    if (response && response.ok) {{ const copy = response.clone(); caches.open(CACHE).then(cache => cache.put(request, copy)); }}
    return response;
  }}).catch(() => caches.match(request, {{ ignoreSearch: true }}).then(hit => hit || (request.mode === 'navigate' ? caches.match('index.html') : Response.error()))));
}});
"""
(COURSE / "sw.js").write_text(sw)
print(f"mlsys/sw.js: {len(files)} files, cache mlsys-{version}")
