// Scope inventory, not a visual/scientific correctness certificate.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const originalCourses=new Set('dl irs asmd asw bi bigdata dm ise netprog oa pm reti-lm sap spe visione'.split(' '));
const files=execFileSync('git',['ls-files','-z','--','*.html'],{cwd:root,encoding:'utf8'}).split('\0').filter(f=>f&&!/^(review|dev|node_modules)\//.test(f));
const pages=files.map(file=>{const source=fs.readFileSync(path.join(root,file),'utf8'),course=file.includes('/')?file.split('/')[0]:'(root)';
 const figures=[...source.matchAll(/<figure\b[\s\S]*?<\/figure>/g)].map((m,i)=>({index:i+1,label:m[0].match(/<figcaption[^>]*>\s*<b>([^<]+)/)?.[1]||null,sha256:crypto.createHash('sha256').update(m[0]).digest('hex'),generatedIds:[...m[0].matchAll(/data-generated-diagram="([^"]+)"/g)].map(m=>m[1]),svg:(m[0].match(/<svg\b/g)||[]).length,images:(m[0].match(/<img\b/g)||[]).length,status:'requires-current-visual-and-semantic-review'}));
 return {file,course,title:source.match(/<title[^>]*>([\s\S]*?)<\/title>/)?.[1]||null,isIndex:path.basename(file)==='index.html',inOriginal208PageScope:originalCourses.has(course)&&/^cap-.*\.html$/.test(path.basename(file)),figures,inlineSvg:(source.match(/<svg\b/g)||[]).length,images:(source.match(/<img\b/g)||[]).length,scripts:(source.match(/<script\b/g)||[]).length,contentReview:'not-certified'};
});
const groups=[...new Set(pages.map(p=>p.course))].sort().map(course=>{const p=pages.filter(p=>p.course===course);return {course,pages:p.length,nonIndexPages:p.filter(p=>!p.isIndex).length,figures:p.reduce((n,p)=>n+p.figures.length,0),inlineSvg:p.reduce((n,p)=>n+p.inlineSvg,0),images:p.reduce((n,p)=>n+p.images,0),generatedFigures:p.reduce((n,p)=>n+p.figures.filter(f=>f.generatedIds.length).length,0)}});
const report={scope:'All tracked site HTML except development/review pages; static source counts, excluding diagrams created at runtime or external SVG assets.',originalScopePages:pages.filter(p=>p.inOriginal208PageScope).length,originalScopeFigures:pages.filter(p=>p.inOriginal208PageScope).reduce((n,p)=>n+p.figures.length,0),pages:pages.length,figures:groups.reduce((n,g)=>n+g.figures,0),groups,records:pages};
fs.writeFileSync(path.join(root,'review/notes-inventory.json'),JSON.stringify(report,null,2));
const rows=groups.map(g=>`| ${g.course} | ${g.pages} | ${g.figures} | ${g.inlineSvg} | ${g.images} | ${g.generatedFigures} |`).join('\n');
fs.writeFileSync(path.join(root,'review/notes-inventory.md'),`# Full-site scope inventory\n\nThis is a source inventory, **not proof that the content or figures are correct**. Generated SVG counts likewise do not establish approval. Per-figure source hashes are recorded in [notes-inventory.json](notes-inventory.json) so subsequent reviews can be tied to an exact version. Runtime widget graphics and externally linked SVG assets need separate review.\n\n${report.pages} tracked HTML pages; ${report.figures} figure elements. The original fifteen-course scope remains ${report.originalScopePages} chapters and ${report.originalScopeFigures} figures. No course is excluded from the broader active goal by the original audit boundary.\n\n| Directory | HTML pages | Figures | Inline SVG | img tags | Generated figures |\n| --- | ---: | ---: | ---: | ---: | ---: |\n${rows}\n\n## Evidence boundaries\n\n- Historical fifteen-course markup/layout repairs: [first revision report](report.md). This does not certify all scientific content.\n- DL editorial revision: [comparison](dl-generated.html), [presets](presets/).\n- Current cross-course replacements: [preview](cross-course/), [source and slide notes](../dev/diagrams/CROSS-COURSE.md).\n- Remaining work includes current visual review of all other figures, graph/text agreement, responsive content outside figures, runtime widgets, and courses outside the first fifteen.\n- Production approval for the current preview is still outstanding.\n`);
console.log(JSON.stringify({pages:report.pages,figures:report.figures,originalScopePages:report.originalScopePages,originalScopeFigures:report.originalScopeFigures,groups},null,2));
