// Build-time preview only: raster reference beside repository-native SVG.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'review/editorial-reference');
const models=require('./dl.cjs').filter(d=>['2.4','3.1','7.3','8.4'].includes(d.plate));
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
fs.mkdirSync(out,{recursive:true});
const cards=models.map(d=>{
  fs.writeFileSync(path.join(out,d.id+'.svg'),d.svg());
  const file=fs.readdirSync(path.join(root,'dl')).find(f=>f.startsWith('cap-'+d.plate.split('.')[0].padStart(2,'0')+'-')&&f.endsWith('.html'));
  return `<article><h2><span>${d.plate}</span> / ${({'2.4':'AUTODIFF','3.1':'NEURON','7.3':'INCEPTION','8.4':'GRU'})[d.plate]}</h2><figure class="lk-fig"><div class="figure-diagram" tabindex="0" role="region" aria-label="Scrollable diagram">${d.svg()}</div><figcaption>${escape(d.caption)}</figcaption></figure><a href="../../dl/${file}">Open chapter</a></article>`;
}).join('\n');
fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DL — art direction to SVG</title><link rel="stylesheet" href="../../dl/assets/lesson-kit.css"><link rel="stylesheet" href="../../assets/course-figures.css"><style>body{margin:0;background:var(--lk-paper);color:var(--lk-ink);font:17px/1.65 var(--lk-font)}main{max-width:1500px;margin:auto;padding:24px}h1,h2{font-family:var(--lk-display);font-weight:600}h1{font-size:32px}h2{font-size:22px}h2 span{color:var(--lk-vermilion)}a{color:var(--lk-cobalt)}p{max-width:85ch}.reference{display:block;width:100%;height:auto}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:36px;margin-top:40px}article{min-width:0}.lk-fig{margin:20px 0;text-align:left}.lk-fig svg{width:700px}.notice{color:var(--lk-vermilion);font:14px/1.5 var(--lk-mono)}@media(max-width:1050px){.grid{grid-template-columns:minmax(0,1fr)}}@media(max-width:640px){main{padding:16px}}</style><main><h1>FROM ART DIRECTION TO SVG</h1><p>Generated composition reference first, then four code-native reconstructions. The SVGs use the lesson's original font stack and paper/ink tokens. Only the reference is a raster image.</p><p class="notice">Preview only. The generated reference contains formula/connection inaccuracies; the reconstructed SVGs follow the chapter and slides instead.</p><p><a href="prompt.md">Exact generation prompt and corrections</a> · <a href="../dl-generated.html">Full DL comparison</a></p><img class="reference" src="concept.png" width="1536" height="1024" alt="AI-generated editorial direction for autodiff, neuron, Inception and a two-stage GRU; not authoritative mathematical content"><div class="grid">${cards}</div></main></html>`);
console.log('Editorial reference preview: '+out);
