// Repository-native, deterministic SVG. Edges attach to named node ports, never free endpoints.
const assert=require('node:assert/strict');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
class Diagram {
  constructor(id,height,title,width=700){this.width=width;this.id=id;this.height=height;this.title=title;this.nodes=new Map();this.edges=[];this.labels=[];}
  node(id,x,y,w,h,lines,options={}){assert(!this.nodes.has(id),'Duplicate node '+id);this.nodes.set(id,{id,x,y,w,h,lines:lines.split('|'),...options});return this;}
  label(x,y,text,color='cobalt'){this.labels.push({x,y,text,color});return this;}
  edge(from,to,via=[],color='cobalt',dash=false){this.edges.push({from,to,via,color,dash});return this;}
  connect(from,to,color='cobalt',dash=false){return this.edge(from+'.toward-'+to,to+'.toward-'+from,[],color,dash);}
  port(ref){const [id,port='E']=ref.split('.'),n=this.nodes.get(id);assert(n,'Missing node '+id);if(port.startsWith('toward-')){const other=this.nodes.get(port.slice(7));assert(other,'Missing straight-edge target '+port);const dx=other.x+other.w/2-n.x-n.w/2,dy=other.y+other.h/2-n.y-n.h/2;assert(dx||dy,'Coincident node centers');const t=n.shape==='circle'?(n.w/2)/Math.hypot(dx,dy):Math.min(dx?Math.abs(n.w/2/dx):Infinity,dy?Math.abs(n.h/2/dy):Infinity);return [n.x+n.w/2+dx*t,n.y+n.h/2+dy*t]}if(n.ports?.[port])return [n.x+n.ports[port][0],n.y+n.ports[port][1]];const ports={N:[n.x+n.w/2,n.y],NW:[n.x+n.w/4,n.y],NE:[n.x+3*n.w/4,n.y],S:[n.x+n.w/2,n.y+n.h],E:[n.x+n.w,n.y+n.h/2],W:[n.x,n.y+n.h/2]};if(n.matrix){const rows=n.matrix.length,cols=n.matrix[0].length;if(Number.isInteger(n.row))ports.rowE=[n.x+n.w,n.y+(n.row+.5)*n.h/rows];if(Number.isInteger(n.col))ports.colS=[n.x+(n.col+.5)*n.w/cols,n.y+n.h];if(n.cell)ports.cellS=[n.x+(n.cell[1]+.5)*n.w/cols,n.y+(n.cell[0]+1)*n.h/rows];}assert(ports[port],'Missing port '+ref);return ports[port];}
  validate(){for(const n of this.nodes.values()){assert(n.x>=0&&n.y>=0&&n.x+n.w<=this.width&&n.y+n.h<=this.height,'Node outside viewBox '+n.id);assert(this.edges.some(e=>e.from.split('.')[0]===n.id||e.to.split('.')[0]===n.id),'Disconnected node '+n.id);}for(const e of this.edges)for(const [x,y]of [this.port(e.from),...e.via,this.port(e.to)])assert(x>=0&&x<=this.width&&y>=0&&y<=this.height,'Edge outside viewBox');return this;}
  svg(){this.validate();const out=[`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${this.width} ${this.height}" style="width:${this.width}px" role="img" aria-label="${esc(this.title)}" data-generated-diagram="${this.id}" font-family="var(--lk-mono)">`,`<title>${esc(this.title)}</title>`,`<defs>`];for(const c of ['cobalt','vermilion'])out.push(`<marker id="${this.id}-${c}" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10Z" fill="var(--lk-${c})"/></marker>`);out.push('</defs>');
    for(const e of this.edges){const points=[this.port(e.from),...e.via,this.port(e.to)];if(['dl-8-4','dl-8-5'].includes(this.id))out.push(`<path d="M${points.map(p=>p.join(' ')).join('L')}" fill="none" stroke="var(--lk-paper)" stroke-width="5"/>`);out.push(`<path data-from="${e.from}" data-to="${e.to}" d="M${points.map(p=>p.join(' ')).join('L')}" fill="none" stroke="var(--lk-${e.color})" stroke-width="${this.strokeWidth||1.7}" ${e.dash?'stroke-dasharray="5 4"':''} marker-end="url(#${this.id}-${e.color})"/>`);}
    for(const [x,y] of this.junctions||[])out.push(`<circle cx="${x}" cy="${y}" r="3" fill="var(--lk-cobalt)"/>`);
    for(const n of this.nodes.values()){const c=n.color||'cobalt';out.push(`<g data-node="${n.id}">`);if(n.matrix){const rows=n.matrix.length,cols=n.matrix[0].length;for(let i=0;i<rows;i++)for(let j=0;j<cols;j++){let selected=n.row===i||n.col===j||n.cell?.join(',')===[i,j].join(',');out.push(`<rect x="${n.x+j*n.w/cols}" y="${n.y+i*n.h/rows}" width="${n.w/cols}" height="${n.h/rows}" fill="var(--lk-paper-light)" stroke="var(--lk-${selected?'vermilion':'rule-soft'})" stroke-width="${selected?2:1}"/><text x="${n.x+(j+.5)*n.w/cols}" y="${n.y+(i+.5)*n.h/rows+5}" text-anchor="middle" fill="var(--lk-${selected?'vermilion':'cobalt'})" font-size="15">${n.matrix[i][j]}</text>`);}}
      else {if(n.shape==='circle'){assert(n.w===n.h,'Circular nodes must be square');out.push(`<circle cx="${n.x+n.w/2}" cy="${n.y+n.h/2}" r="${n.w/2}" fill="var(--lk-paper)" stroke="var(--lk-${c})" stroke-width="1.5"/>`)}else if(n.shape!=='plain')out.push(`<rect x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="3" fill="var(--lk-paper)" stroke="var(--lk-${c})" stroke-width="1.5"/>`);n.lines.forEach((s,i)=>out.push(`<text x="${n.x+n.w/2}" y="${n.y+n.h/2+5+(i-(n.lines.length-1)/2)*21}" text-anchor="middle" font-size="14" fill="var(--lk-${n.color==='vermilion'?'vermilion':'ink'})">${esc(s)}</text>`));}out.push('</g>');}
    for(const l of this.labels)out.push(`<text x="${l.x}" y="${l.y}" text-anchor="middle" font-size="14" fill="var(--lk-${l.color})">${esc(l.text)}</text>`);out.push('</svg>');return out.join('\n');}
}
module.exports={Diagram};
