const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),model=require('../../cybersecurity/assets/agent-policy-model.js'),{createRenderer}=require('./render.cjs');
const root=path.resolve(__dirname,'../..'),asset=root+'/cybersecurity/assets/diagrams/cyber-agent-enforcement.svg';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const diagram={id:'cyber-agent-enforcement',title:'A proposed action must pass an external policy check before dispatch',source:`flowchart TB
Q["Request + authenticated account"] --> P["Model proposal"]
P --> G{"Policy check"}
G -->|"deny"| B["Blocked / no dispatch"]
G -->|"allow"| T["Dispatch permitted operation"]
T -->|"reply"| F["Finished"]
T -->|"tool result"| O["Observation: untrusted content"]
O --> P
style B stroke:#B83D2D
style G stroke:#B83D2D
linkStyle 2 stroke:#B83D2D`,overrides:{nodeSpacing:25,rankSpacing:45,wrappingWidth:285},requiredText:['Request + authenticated account','Model proposal','Policy check','Blocked / no dispatch','Dispatch permitted operation','Observation: untrusted content','Finished','deny','allow','tool result','reply']};
function widget(){return `<div id="react-flow" data-agent-widget>
<h4>Step through five scripted proposals</h4>
<p>No LLM or real tool is executed. The trace applies the small policy below to prewritten proposals; it is not an attack benchmark or a production security boundary.</p>
<fieldset disabled style="background:#F3EFE3;border:1px solid #1546B8;padding:12px;min-width:0;display:flex;flex-wrap:wrap;gap:12px"><legend>Policy trace</legend><label style="display:block;max-width:100%">Scenario <select style="display:block;max-width:100%;font:inherit">${model.scenarios().map(s=>`<option value="${s.id}">${esc(s.label)}</option>`).join('')}</select></label> <button type="button" data-agent-next>Next step</button> <button type="button" data-agent-reset>Reset trace</button></fieldset>
<p role="status" aria-live="polite" data-agent-status>Interactive controls require JavaScript; the complete worked traces are available below.</p>
<div data-agent-live hidden><h4></h4><p></p></div>
${model.scenarios().map(s=>{const r=model.run(s.id);return `<details data-agent-case="${s.id}"><summary>${esc(s.label)} — ${r.outcome}; tool calls: ${r.toolCalls}, replies: ${r.replies}</summary><ol>${r.trace.map(t=>`<li><strong>${t.state}:</strong> ${esc(t.detail)}</li>`).join('')}</ol></details>`;}).join('\n')}
</div>`;}
function content(r){return `<div id="agent-enforcement">
<p>A conversational interface may retain history or use tools; “chatbot” does not imply statelessness or low impact. An agentic application lets a model propose actions within a surrounding execution system. Those actions can access local resources, remote services or the user-facing reply channel. Location alone does not determine authorization.</p>
<h3>ReAct is an interaction pattern, not an access-control policy</h3>
<p><a href="https://arxiv.org/abs/2210.03629">Yao et al., ReAct</a> interleave generated reasoning traces and task-specific actions with observations from the environment. Their question-answering examples use a Wikipedia interface; the action space also includes finishing with an answer. The paper does not establish that every action is an external disclosure or that this loop itself enforces confidentiality.</p>
<p>A model-produced tool call is a proposal until an executor dispatches it. Inspect actual arguments, authenticated actor, target resource and recipient. Returning an answer can disclose data too; a tool observation is an input channel for untrusted content. Do not treat instructions found in a retrieved result as new authorization.</p>
<figure data-static-diagram="${diagram.id}" style="max-width:100%;margin:1.6rem 0"><div role="region" tabindex="0" aria-label="Agent proposal, policy check and dispatch: scroll horizontally" style="max-width:100%;overflow-x:auto;background:#F3EFE3;border:1px solid #C9C3B6;padding:12px;box-sizing:border-box"><img src="../cybersecurity/assets/diagrams/${diagram.id}.svg" width="${r.width}" height="${r.height}" alt="Every proposed operation is checked before dispatch; tool results return to proposal, while a permitted reply finishes." style="display:block;width:${r.width}px;max-width:none;height:auto;margin:auto"></div><figcaption>Illustrative enforced architecture, not a reproduction of ReAct or CaMeL. The return arrow carries observations, not permission to bypass the next check. A denial prevents that dispatch; it does not undo earlier calls. Both tool operations and final replies pass through the gate. These guarantees assume the gate cannot be bypassed and that identity, labels and policy are correct.</figcaption></figure>
<h3>Make the policy explicit</h3>
<p>For this teaching example, accounts are A and B and a fictional record belongs to A. The local record store permits access only to the owner. Search accepts public data only. Replies may contain public data or the requesting account’s own record. Labels and ownership are trusted metadata in the example, not claims supplied by the model. A real system must establish provenance, authorization, purpose and complete mediation; this tiny label check does not solve those problems.</p>
<pre tabindex="0" role="region" aria-label="Illustrative policy before dispatch"><code>proposal = model_proposal(context)
decision = policy(authenticated_actor, trusted_labels, proposal)
if not decision.allow: stop_without_dispatch()
else: result = dispatch(proposal)
# Tool observations may influence a later proposal, but do not grant authority.
# A final reply is also checked before delivery.</code></pre>
${widget()}
<p>The local/other-account case is denied even though no external server is involved. The public search is allowed even though it is external. In the returned-instruction case, one public search has already happened before a second, private-data proposal is blocked. The worked traces compute those counts from the policy; they do not infer security from tool names.</p>
<p><a href="../cybersecurity/assets/agent-policy-model.js" download>Download the deterministic policy and scenarios</a>. Client-side controls only teach the example; readers can modify them, so they must never be used to enforce access to real data.</p>
<h3>System enforcement and learned behavior are different</h3>
<p><a href="https://arxiv.org/html/2503.18813v2">Debenedetti et al., CaMeL</a> separate control and data flows and enforce tool-call policies using capabilities. That supports placing enforcement outside a model’s natural-language promises. It is not a universal solution: the paper specifies threat assumptions and discusses policy specification, declassification, side channels and attacks outside its data-flow scope. The simple example here is not CaMeL and inherits none of its experimental results or security proofs.</p>
<details data-agent-check><summary>Does a blocked second proposal undo the first tool call?</summary><p>No. In the returned-instruction trace, the public search already ran. The policy blocks the later private-data dispatch only. Check complete traces, not just the final state, when assessing exposure or side effects.</p></details>
</div>`;}
const residency='<p>On-device inference can avoid sending model inputs to a remote inference provider. It does not by itself establish confidentiality: local access permissions, storage, logs, synchronization and the reply recipient also matter. External tools add recipients and data flows to assess; a permitted public query need not disclose private context. Enforce the applicable policy outside the model rather than relying on a promise to filter data.</p>';
const recap='<p>ReAct interleaves reasoning, actions and observations. In an application, distinguish the model’s proposal from actual tool execution or reply delivery. Tool results can contain untrusted instructions; local resources can be accessed without authorization; external queries can be permitted. Assess actor, resource, payload, recipient and purpose, and enforce policy before dispatch. The teaching trace checks both tool calls and final replies; a blocked later proposal does not reverse earlier effects.</p>';
function next(e,html,r){let s=html;const rew=e.file.startsWith('cybersecurity-reworked/');if(rew){const re=/<section id="s14">[\s\S]*?<\/section>/;assert(re.test(s));s=s.replace(re,`<section id="s14">\n<h2>14. Agentic AI: proposals, tools and enforcement</h2>\n${content(r)}\n</section>`).replace(/(<a href="#s14">)[^<]*(<\/a>)/,'$1Agentic AI: proposals, tools and enforcement$2');}else{const re=/<section id="s16">[\s\S]*?(?=<!-- BEGIN DIFFERENTIAL PRIVACY -->)/;assert(re.test(s));s=s.replace(re,`<section id="s16">\n<h2>16. Agentic AI: Architecture and Privacy Risks</h2>\n${content(r)}\n`);}
const call=/\/\/ State explorer: Agentic AI privacy leakage flow\s*LessonKit\.stateExplorer\('#react-flow', \{[\s\S]*?\n\}\);/;if(call.test(s))s=s.replace(call,'// Agent policy traces are implemented by the shared model/widget assets.');else assert(s.includes('// Agent policy traces are implemented by the shared model/widget assets.'));
for(const file of ['agent-policy-model.js','agent-policy-widget.js'])if(!s.includes('src="../cybersecurity/assets/'+file+'"'))s=s.replace('</body>','<script defer src="../cybersecurity/assets/'+file+'"></script>\n</body>');
s=s.replace(/<p>Local inference ensures patient data never leaves the device[\s\S]*?<\/p>/,residency).replace(/<p>Without tool calling, on-device inference makes privacy[\s\S]*?<\/p>/,residency);
s=s.replace('local inference keeps patient data on-device, never sent to the cloud during normal operation.','local inference can avoid remote inference requests. Whether patient data stays on-device also depends on tools, logs, synchronization and deployment settings.');
s=s.replace('A <em>tool</em> = an external interface with a unique ID, a description, and a function signature. The agent has <strong>4 safe tools</strong> (local patient DB, medical-history access, lab-results retrieval, appointment scheduling) and <strong>1 unsafe tool</strong> (web search — queries leave to external servers).','In the course scenario, a <em>tool</em> is a callable interface identified by its name, description and function signature. Four tools access patient records or appointments; web search sends queries to an external service. The slides label these groups “safe” and “unsafe” according to that scenario’s data-flow assumptions, not a general authorization guarantee. Each operation still requires a check of the actor, payload and recipient.');
s=s.replace('The agent has 4 safe tools (local DB, medical history, lab results, appointments) and 1 unsafe tool (web search).','The course scenario has four internal record/appointment tools and one external search tool. The slides’ “safe”/“unsafe” labels describe this scenario’s data-flow assumptions, not a general authorization guarantee; actor, payload and recipient must still be checked.');
const q=/(<summary>What is the ReAct architecture and why is it relevant to privacy\?<\/summary>\s*)<p>[\s\S]*?<\/p>/;assert(q.test(s));s=s.replace(q,(_,head)=>head+recap);
return s;}
function dimensions(){const s=fs.readFileSync(asset,'utf8');return {width:Number(s.match(/\bwidth="([\d.]+)"/)[1]),height:Number(s.match(/\bheight="([\d.]+)"/)[1])};}
if(require.main===module)(async()=>{const renderer=await createRenderer();let r;try{r=await renderer.render(diagram);if(process.argv.includes('--check'))assert.equal(fs.readFileSync(asset,'utf8'),r.svg+'\n');else fs.writeFileSync(asset,r.svg+'\n');}finally{await renderer.close();}let patch='*** Begin Patch\n';for(const e of require('./transfer-sources.cjs')){const f=root+'/'+e.file,old=fs.readFileSync(f,'utf8'),s=next(e,old,r);if(process.argv.includes('--check'))assert.equal(s,old);else if(s!==old)patch+='*** Update File: '+f+'\n'+require('./transfer-content.cjs').hunks(old,s);}if(process.argv.includes('--check'))console.log('Agent architecture, policy traces, widget assets and recap synchronized');else process.stdout.write(patch+'*** End Patch\n');})().catch(e=>{console.error(e);process.exitCode=1;});
module.exports={model,diagram,asset,dimensions,content,next};
