const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),plot=require('./dp-plot.cjs'),{createRenderer}=require('./render.cjs');
const root=path.resolve(__dirname,'../..'),dir=root+'/cybersecurity/assets/diagrams/',book='https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf',lm='https://arxiv.org/abs/2110.06500';
const diagram={id:'cyber-dp-scope',title:'DP training protects its declared dataset, not automatically fresh context',source:`flowchart TB
D["Protected dataset D"] --> M["DP training M(D)"]
M --> W["Released model θ"]
W --> G["Generate text / tool arguments"]
C["Fresh private context c"] --> G
style C stroke:#B83D2D
linkStyle 3 stroke:#B83D2D`,overrides:{nodeSpacing:40,rankSpacing:40,wrappingWidth:290},requiredText:['Protected dataset D','DP training M(D)','Released model θ','Generate text / tool arguments','Fresh private context c']};
function figure(id,r,alt,caption){return `<figure data-dp-figure="${id}" data-static-${id===diagram.id?'diagram':'plot'}="${id}" style="max-width:100%;margin:1.6rem 0"><div role="region" tabindex="0" aria-label="${alt}: scroll horizontally" style="max-width:100%;overflow-x:auto;background:#F3EFE3;border:1px solid #C9C3B6;padding:12px;box-sizing:border-box"><img src="../cybersecurity/assets/diagrams/${id}.svg" width="${r.width}" height="${r.height}" alt="${alt}" style="display:block;width:${r.width}px;max-width:none;height:auto;margin:auto"></div><figcaption>${caption}</figcaption></figure>`;}
function content(r){const a=plot.render();return `<!-- BEGIN DIFFERENTIAL PRIVACY -->
<div id="dp-protection">
<h3>Differential privacy: specify what is protected</h3>
<p>DP is a property of a randomized mechanism, not a synonym for adding noise. With ε≥0 and 0≤δ&lt;1, for all neighboring datasets D, D′ and measurable output events S:</p>
<pre tabindex="0" role="region" aria-label="Differential privacy definition"><code>Pr[M(D) ∈ S] ≤ exp(ε) · Pr[M(D′) ∈ S] + δ</code></pre>
<p>Probabilities are over the mechanism’s randomness. Pure DP has δ=0; approximate DP allows δ&gt;0. Specify adjacency: adding/removing one record, replacing one record, or changing one person’s contributions are different units. A record-level bound is not automatically a person-level bound when a person contributes multiple records. DP limits distinguishability; it does not promise that every inference about someone is impossible. See <a href="${book}#page=21">Dwork &amp; Roth, Definition 2.4 and group privacy</a>.</p>
<h4>Text output is compatible with DP</h4>
<p>A data-independent transformation of a DP release preserves its guarantee, including a transformation into text. For a DP-trained model, generation is post-processing with respect to the protected training dataset if the downstream procedure has no additional access to it. Hold other inputs fixed across neighboring datasets. This protects neither new context by default nor records previously exposed by a non-private pretraining stage. See <a href="${book}#page=23">post-processing, Proposition 2.1</a>.</p>
<p><a href="${lm}">Yu et al., Differentially Private Fine-tuning of Language Models</a> evaluate private fine-tuning for natural-language generation, including GPT-2 on DART. This is a concrete counterexample to the slides’ claim that DP applies only to statistical aggregates. Their guarantee concerns the specified fine-tuning data and privacy accounting, not arbitrary secrets in future prompts. No language model is trained or benchmark rerun here.</p>
${figure(diagram.id,r,'DP training and the separate live-context input','Blue shows the protected training-data path. Red shows an additional context input, not a finding that the training guarantee failed. For fixed c, generation can retain DP with respect to D while exposing c completely. Protecting c requires its own mechanism or enforced disclosure controls. This diagram assumes an appropriately DP-trained release; merely adding noise somewhere does not establish that premise.')}
<h4>A fully enumerated one-bit example</h4>
<p>Let neighboring inputs be x=0 and x=1: one protected bit is replaced. Randomized response returns y=x with probability p=0.75 and y=1−x otherwise. The largest probability ratio is p/(1−p)=3, so pure ε=ln(3)≈1.0986. This is an educational finite mechanism, not an LLM, an empirical attack score or a recommended deployment budget.</p>
<pre tabindex="0" role="region" aria-label="Four randomized-response release procedures"><code>y = randomized_response(x, p)
text:  return "YES" if y == 1 else "NO"
reuse: return (y, y)
fresh: return (y, randomized_response(x, p))  # independent fresh draw
raw:   return (y, x)                        # accesses the protected bit again</code></pre>
${figure('cyber-dp-distributions',a,'Four exact output distributions for neighboring bits','Blue and vermilion bars compare the two neighboring inputs, not correct and incorrect predictions. Every outcome is shown, including zero-probability outcomes. Repeating one result keeps the same bound; independent fresh access composes. Appending the raw protected bit gives disjoint supports. Heights are calculated probabilities, not sampled frequencies; the code contains full-precision values.')}
<div role="region" tabindex="0" aria-label="Randomized response privacy bounds: scroll horizontally" style="max-width:100%;overflow-x:auto"><table data-dp-results style="min-width:680px;table-layout:fixed;width:100%"><caption>Exact worst-case pure-DP bounds for this two-input mechanism</caption><thead><tr><th scope="col">Release</th><th scope="col">Operation</th><th scope="col">Largest ratio</th><th scope="col">ε</th></tr></thead><tbody>
${a.rows.map(row=>`<tr data-mode="${row.id}"><th scope="row">${row.label}</th><td>${row.meaning}</td><td>${Number.isFinite(row.ratio)?row.ratio.toFixed(0):'∞'}</td><td>${Number.isFinite(row.epsilon)?row.epsilon.toFixed(4):'No finite bound'}</td></tr>`).join('\n')}
</tbody></table></div>
<p>For two fresh releases, event (0,0) has probabilities 0.5625 and 0.0625: ratio 9, giving 2ln(3). For reuse, (0,0) has probabilities 0.75 and 0.25: ratio 3. With raw output, event “last bit is 0” has probabilities 1 and 0. It violates the DP inequality for every finite ε and δ&lt;1. A copied fresh context secret has the same problem <em>with respect to that secret</em>, even if a separate training-data guarantee remains intact.</p>
<h4>Account for data access, not the number of displayed answers</h4>
<p>Reusing one DP release is post-processing. New private-data accesses require accounting; basic composition adds the ε and δ budgets of the component mechanisms under its assumptions. These cases cannot be distinguished by counting chat turns alone. See <a href="${book}#page=47">composition, Theorem 3.16</a>. DP and recipient authorization answer different questions and can be used together.</p>
<p><a href="../cybersecurity/assets/dp-model.cjs" download>Download the exact finite-distribution model</a>. It enumerates outcomes without sampling or accessing personal data; it is not a production privacy accountant or a secure random-number implementation.</p>
<details data-dp-check><summary>Does generating ten sentences from one DP-trained model necessarily spend ten training privacy budgets?</summary><p>No. A finite transcript using only that released model, public or held-fixed inputs, and fresh data-independent randomness is post-processing of the same release. Further access to protected records or separately trained releases needs its own analysis. New private prompt data is not automatically covered by the model’s training guarantee.</p></details>
</div>
<!-- END DIFFERENTIAL PRIVACY -->`;}
const answer='<p>DP bounds output-event probabilities for neighboring datasets: Pr[M(D) ∈ S] ≤ exp(ε) Pr[M(D′) ∈ S] + δ. State the protected unit and adjacency. It can protect language-model training or fine-tuning and survives data-independent post-processing into text. It does not automatically protect fresh private context, authorize tool recipients or cover additional raw-data access. Reusing one DP release and making independent new private-data queries have different accounting.</p>';
function next(e,html,r){let s=html;if(e.file.startsWith('cybersecurity-reworked/')){s=s.replace(/<section id="s15">[\s\S]*?<\/section>/,`<section id="s15">\n<h2>15. Differential privacy: guarantees and scope</h2>\n${content(r)}\n</section>`).replace(/(<a href="#s15">)[^<]*(<\/a>)/,'$1Differential privacy: guarantees and scope$2');const q=/(<summary>What is differential privacy, and why is it insufficient for agentic LLMs\?<\/summary>\s*)<p>[\s\S]*?<\/p>/;assert(q.test(s));s=s.replace(q,(_,head)=>head+answer);}else{const marker=/<!-- BEGIN DIFFERENTIAL PRIVACY -->[\s\S]*?<!-- END DIFFERENTIAL PRIVACY -->/;if(marker.test(s))s=s.replace(marker,content(r));else{const section=/<section id="s16">[\s\S]*?<\/section>/;assert(section.test(s));s=s.replace(section,old=>old.replace('</section>',content(r)+'\n</section>'));}}return s;}
function dimensions(){const s=fs.readFileSync(dir+diagram.id+'.svg','utf8');return {width:Number(s.match(/\bwidth="([\d.]+)"/)[1]),height:Number(s.match(/\bheight="([\d.]+)"/)[1])};}
if(require.main===module)(async()=>{const renderer=await createRenderer();let r;try{r=await renderer.render(diagram);for(const [name,svg] of [[diagram.id,r.svg+'\n'],['cyber-dp-distributions',plot.render().svg]]){const f=dir+name+'.svg';if(process.argv.includes('--check'))assert.equal(fs.readFileSync(f,'utf8'),svg);else fs.writeFileSync(f,svg);}}finally{await renderer.close();}let patch='*** Begin Patch\n';for(const e of require('./transfer-sources.cjs')){const f=root+'/'+e.file,old=fs.readFileSync(f,'utf8'),s=next(e,old,r);if(process.argv.includes('--check'))assert.equal(s,old);else if(s!==old)patch+='*** Update File: '+f+'\n'+require('./transfer-content.cjs').hunks(old,s);}if(process.argv.includes('--check'))console.log('DP diagrams, probabilities, bounds, sections and recap synchronized');else process.stdout.write(patch+'*** End Patch\n');})().catch(e=>{console.error(e);process.exitCode=1;});
module.exports={diagram,plot,content,next,dimensions,dir};
