const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process'),c=require('./dp-content.cjs'),m=c.plot.model;
const close=(a,b)=>assert(Math.abs(a-b)<1e-11,`${a} != ${b}`);let events=0,distributions=0,scopeChecks=0;
for(let i=0;i<50;i++){const p=0.5+i/100,q=1-p,rows=m.examples({p}),oracles=[[[p,q],[q,p]],[[p,0,0,q],[q,0,0,p]],[[p*p,p*q,p*q,q*q],[q*q,p*q,p*q,p*p]],[[p,0,q,0],[0,q,0,p]]];
 rows.forEach((r,j)=>{for(const [actual,expected] of [[r.zero,oracles[j][0]],[r.one,oracles[j][1]]]){assert.equal(actual.length,expected.length);actual.forEach((a,k)=>close(a,expected[k]));close(actual.reduce((s,a)=>s+a,0),1);distributions++;}
 let eventRatio=1;for(let mask=0;mask<2**r.outcomes.length;mask++){let a=0,b=0;for(let k=0;k<r.outcomes.length;k++)if(mask&(1<<k)){a+=r.zero[k];b+=r.one[k];}for(const [u,v] of [[a,b],[b,a]]){events++;if(u>0)eventRatio=Math.max(eventRatio,v===0?Infinity:u/v);if(Number.isFinite(r.epsilon))assert(u<=Math.exp(r.epsilon)*v+1e-12);}}
 if(j===3){assert.equal(eventRatio,Infinity);assert.equal(r.epsilon,Infinity);close(r.zero[0]+r.zero[2],1);close(r.one[0]+r.one[2],0);}else{close(eventRatio,r.ratio);close(r.epsilon,(j===2?2:1)*Math.log(p/q));if(p>0.5)assert(r.zero[0]>Math.exp(r.epsilon-1e-6)*r.one[0]);}
 });
 // Independent context c is copied beside the RR release of x. Common support:
 // NO/c0, YES/c0, NO/c1, YES/c1. The guarantee depends on which input varies.
 const withContext=(x,context)=>{const d=m.distribution(p,'text',x).probabilities;return context===0?[...d,0,0]:[0,0,...d];};
 for(const context of [0,1]){close(m.bound(withContext(0,context),withContext(1,context)).epsilon,Math.log(p/q));scopeChecks++;}
 for(const x of [0,1]){assert.equal(m.bound(withContext(x,0),withContext(x,1)).epsilon,Infinity);scopeChecks++;}
}
const defaults=m.examples();assert.deepEqual(defaults.map(r=>r.ratio),[3,3,9,Infinity]);const copy=m.examples();copy[0].zero[0]=0;assert.equal(m.examples()[0].zero[0],0.75);
const invalid=[()=>m.examples(null),()=>m.examples([]),()=>m.examples({epsilon:1}),...[-1,0,0.4999,0.991,1,NaN,Infinity,'0.75'].map(p=>()=>m.examples({p})),()=>m.distribution(.75,'unknown',0),()=>m.distribution(.75,'text',2),()=>m.bound([],[]),()=>m.bound([1],[.5]),()=>m.bound([2,-1],[1,0]),()=>m.bound([NaN],[1]),()=>m.bound([.5,.5],[1])];for(const run of invalid)assert.throws(run);
const dir=process.env.NOTES_DP_EVIDENCE;assert(dir,'Set NOTES_DP_EVIDENCE to the reviewed source directory');const pins={book:'599bb0add9a0ec7bf85a6561dbc7619f45403892a19084eb1fe622352ef91ef7',lm:'7a2cb68240337d709ee446246e4e5f47d3e287a2b20f3546b6f44776d3df8cac'};
const texts={};for(const [name,sha] of Object.entries(pins)){const f=path.join(dir,name+'.pdf');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),sha);texts[name]=execFileSync('pdftotext',['-raw',f,'-'],{encoding:'utf8',maxBuffer:5e6}).replace(/\s+/g,' ');}
assert.match(texts.book,/Definition 2.4/);assert.match(texts.book,/Proposition 2.1 \(Post-Processing\)/);assert.match(texts.book,/Theorem 3.16/);assert.match(texts.lm,/natural language generation tasks/);assert.match(texts.lm,/DART/);
(async()=>{const {parse}=await import('../contracts/node_modules/parse5/dist/index.js'),root=path.resolve(__dirname,'../..');for(const e of require('./transfer-sources.cjs')){const s=fs.readFileSync(root+'/'+e.file,'utf8');assert.equal(c.next(e,s,c.dimensions()),s);const errors=[];parse(s,{onParseError:e=>errors.push(e)});assert.deepEqual(errors,[]);for(const bad of ['DP applies to <strong>statistical aggregates</strong>, not','DP applies to statistical aggregates, not free-text','Differential privacy and why it fails for agents'])assert(!s.includes(bad));assert.equal((s.match(/id="dp-protection"/g)||[]).length,1);}
fs.writeFileSync('/home/ybc/notes-legacy-review-artifacts/dp-test.json',JSON.stringify({distributions,events,scopeChecks,invalid:invalid.length,pins,markup:true,sync:true,scope:'Finite one-bit mechanism and primary-source checks, not a trained LLM or production DP library'},null,2)+'\n');console.log(`${distributions} distributions, ${events} event inequalities, ${scopeChecks} two-input scope checks, ${invalid.length} invalid inputs; tight pure-DP bounds, raw-bit counterexample, two pinned papers, markup and chapter sync passed`);})().catch(e=>{console.error(e);process.exitCode=1;});
