const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),entries=require('./transfer-sources.cjs'),plot=require('./feature-plot.cjs'),model=require('../../cybersecurity/assets/feature-model.cjs');
const definition=require('./transfer-content.cjs').definition,example=require('../../cybersecurity/assets/fgsm-evidence.cjs').illustration;
const source={szegedy:'https://arxiv.org/pdf/1312.6199v4',goodfellow:'https://arxiv.org/pdf/1412.6572v3',schmidt:'https://proceedings.neurips.cc/paper_files/paper/2018/file/f708f064faaf32a43e4d3c784e6af9ea-Paper.pdf',ilyas:'https://arxiv.org/pdf/1905.02175',amich:'https://arxiv.org/pdf/2202.08944v1',stutz:'https://openaccess.thecvf.com/content_CVPR_2019/papers/Stutz_Disentangling_Adversarial_Robustness_and_Generalization_CVPR_2019_paper.pdf'};
function introduction(){return `<p>A classifier assigns an input to a label. Accuracy on sampled test data does not establish stability under every allowed perturbation. An attacker’s objective, input access and constraints determine what counts as a successful adversarial example.</p>
${definition}
<p>In <a href="${source.goodfellow}">Goodfellow et al., Figure 1</a>, one ${example.model} input changes from ${example.cleanClass} (${example.cleanScorePercent}% class score) to ${example.candidateClass} (${example.candidateScorePercent}%) after a perturbation with ε = ${example.epsilon} in that model’s encoding. These are scores for one illustration, not success rates or a guarantee of invisibility for arbitrary images. See <a href="#s4">the model-specific FGSM results</a>.</p>
<h3>What the neuron experiment does—and does not—show</h3>
<p><a href="${source.szegedy}">Szegedy et al., §3</a> found semantically related activating images for both individual high-level units and random linear combinations in their examined networks. This challenges treating individual coordinates as the uniquely meaningful basis. It does not establish that individual neurons can never be interpretable, or that neural networks learn no human-recognizable features.</p>
<p>A feature can be an input-derived function or a representation direction, not necessarily one neuron. Distributed representation, interpretability and robustness are different questions. The useful/non-robust distinction in <a href="#s7">section 7</a> is defined relative to data and allowed perturbations, not by whether a feature looks meaningful to a person.</p>`;}
const why=`<h3>Random corruption is not worst-case perturbation</h3>
<p>A random-noise test averages over a chosen noise distribution; an adversarial robustness claim concerns all allowed changes or an explicitly evaluated attack. Random draws may miss damaging directions, but random noise is not universally harmless. Successful attacks are not necessarily minimal, cheap, imperceptible or guaranteed to transfer.</p>
<p>For a linear score, signed margin and the perturbation budget determine whether a label can change; dimensionality alone is not enough. The exact calculation in <a href="#s7">section 7</a> makes this distinction concrete.</p>
<h3>From model error to system impact</h3>
<p>A manipulated decision can affect integrity; consequences for availability, confidentiality or physical safety depend on how the surrounding application uses that decision and on its other controls. A benchmark misclassification alone does not demonstrate a system intrusion or an accident. Clean accuracy and robustness should therefore be evaluated separately under the intended deployment conditions.</p>`;
const panels=[
 ['H1: Nonlinearity',`<p>Nonlinearity is not necessary for adversarial errors: affine classifiers already admit them when an allowed perturbation can cross their decision boundary. This is a counterexample to necessity, not evidence that nonlinear geometry is irrelevant. See <a href="${source.goodfellow}">Goodfellow et al., §§3–4</a>.</p>`],
 ['H2: Margins and linearity',`<p>Affine maps composed with ReLUs give piecewise-affine logits; softmax probabilities and cross-entropy need not be piecewise affine. A local gradient is a local sensitivity, not a global loss maximizer.</p>
<pre tabindex="0" role="region" aria-label="Exact linear signed-margin bound"><code>s(x) = wᵀx + b; y ∈ {−1, +1}
min_(||δ||∞ ≤ ε) y s(x + δ) = y s(x) − ε ||w||₁</code></pre>
<p>A positive minimum keeps the correct sign throughout this box. A negative minimum gives a wrong-sign witness; zero requires a stated tie rule. Contributions can add across coordinates, but a sufficiently large margin can prevent a flip. Input-domain restrictions can further shrink the box. This is the linear argument behind <a href="${source.goodfellow}">Goodfellow et al., §3</a>, not a universal account of every network.</p>`],
 ['H3: Data requirements',`<p><a href="${source.schmidt}">Schmidt et al. (2018), §§1–2</a> show that robust generalization can need substantially more samples than ordinary generalization in specified data models. Their Gaussian and binary settings behave differently; thresholding can change the binary-model conclusion.</p>
<p>This is not a theorem that every high-dimensional task requires exponentially many examples, nor that all adversarial inputs occur where training data is absent. Distribution, perturbation set and classifier assumptions matter.</p>`],
 ['H4: Useful features',`<p><a href="${source.ilyas}">Ilyas et al., §2</a> distinguish a feature’s clean predictive usefulness from usefulness under a specified adversary. For binary labels and features normalized to mean zero and variance one on D:</p>
<pre tabindex="0" role="region" aria-label="Useful and robustly useful features"><code>Clean usefulness: E_D[y f(x)] ≥ ρ, with ρ > 0
Robust usefulness: E_D[inf_(δ in Δ(x)) y f(x + δ)] ≥ γ, with γ > 0</code></pre>
<p>A feature can genuinely predict labels in D yet lose that correlation under Δ. “Non-robust” does not mean random noise or necessarily an accidental training-only correlation; “robust” does not mean human-interpretable. These are average usefulness criteria, not certificates for every individual prediction. The paper’s footnote 1 explicitly leaves room for other sources of adversarial vulnerability.</p>`],
 ['H5: Distribution shift',`<p>OOD is relative to a reference distribution and an operational detection rule. An OOD score above a threshold is not direct knowledge of the natural data manifold and does not prove the cause of an error.</p>
<p><a href="${source.amich}">Amich &amp; Eshete (2022), §§1 and 2.3</a> report 90% of FGSM and 87% of PGD samples flagged OOD in their preliminary CIFAR-10 study using SSD. These are detector-dependent observations, not a universal fraction across attacks or datasets. Their text does not support the earlier “~75% of adversarial examples” claim as written in these notes; the paper also uses approximately 75% for a different metric, relative robustness after a defense. These experiments were not rerun here.</p>
<p><a href="${source.stutz}">Stutz et al. (2019)</a> also study label-preserving on-manifold adversarial examples, using known or estimated manifolds. Distribution shift and adversarial error are therefore not interchangeable definitions: a shifted input need not be an attack, and manifold membership alone does not establish correct classification.</p>`]
];
function section(){const r=plot.render(),m=r.model;return `<section id="s7">
<h2>7. Why adversarial examples exist: five perspectives and their limits</h2>
<p>The course groups the explanations into five themes. The cited works use different assumptions; their results are not five universal laws or a measured consensus about one cause.</p>
<div class="lk-tabs" data-kit="tabs" data-feature-perspectives><div class="lk-tablist">${panels.map(([title])=>`<button class="lk-tab">${title}</button>`).join('')}</div>
${panels.map(([,body])=>`<div class="lk-tabpanel">${body}</div>`).join('\n')}
</div>
<h3>A calculated example: clean usefulness versus perturbation sensitivity</h3>
<p>This invented distribution contains just two equally likely inputs: y ∈ {−1,+1}, x = (u,v) = (y, ηy), η = ${m.eta}. Define the true label throughout the plotted neighborhood as sign(u). Both f₁(x) = u and f₂(x) = v/η have mean zero, variance one and clean usefulness 1 on this distribution.</p>
<p>Allow ||δ||∞ ≤ ε = ${m.epsilon}. The two panels use exactly the same points and the same δ = (−εy, −εy), preserving the true label. Only the classifier changes. This is a coordinate example, not an image dataset, trained network or claim about human perception.</p>
<figure data-static-plot="cyber-feature-sensitivity" style="max-width:100%;margin:1.6rem 0"><div role="region" tabindex="0" aria-label="Two classifiers on identical inputs: scroll horizontally" style="max-width:100%;overflow-x:auto;background:#F3EFE3;border:1px solid #C9C3B6;padding:12px;box-sizing:border-box"><img src="../cybersecurity/assets/diagrams/cyber-feature-sensitivity.svg" width="${r.width}" height="${r.height}" alt="Identical diagonal perturbations preserve both predictions using u, but flip both using v divided by eta." style="display:block;width:${r.width}px;max-width:none;height:auto;margin:auto"></div>
<figcaption>Equal coordinate scales in both panels. Circles are clean inputs; squares are perturbed inputs; arrows show their displacement. Marker color is the classifier’s prediction, not a changed ground-truth label. Blue shading is the +1 region; the solid boundary is u = 0 on the left and v = 0 on the right. Dashed squares show the complete L∞ budget. The displayed perturbation attains both features’ worst signed scores in this example.</figcaption></figure>
<div role="region" tabindex="0" aria-label="Feature usefulness calculation: scroll horizontally" style="max-width:100%;overflow-x:auto"><table data-feature-scores style="min-width:560px"><caption>Exact two-point model; numerical displays rounded to two decimals</caption><thead><tr><th scope="col">Feature</th><th scope="col">Clean E[yf]</th><th scope="col">Worst E[yf]</th><th scope="col">Candidate predictions (truth −1, +1)</th></tr></thead><tbody>
${m.features.map(f=>`<tr><th scope="row">${f.kind==='u'?'u':'v/η'}</th><td>${f.cleanCorrelation.toFixed(2)}</td><td>${f.worstCorrelation.toFixed(2)}</td><td>${f.candidatePredictions.join(', ')}</td></tr>`).join('\n')}
</tbody></table></div>
<p>The worst usefulness is 1 − ε = ${(1-m.epsilon).toFixed(2)} for u and 1 − ε/η = ${(1-m.epsilon/m.eta).toFixed(2)} for v/η. Both classifiers are correct on the two clean inputs, but only sign(u) remains correct throughout these perturbation boxes. No nonlinearity or shortage of training examples is needed for this particular contrast. The perturbed points leave this toy distribution’s two-point support; the example does not prove that real adversarial images must be OOD. <a href="../cybersecurity/assets/feature-model.cjs" download>Download the model and exact margin formula</a>.</p>
</section>`;}
const quizTitle='What do the five perspectives establish, and which conclusions would overstate the evidence?';
const quiz='<p>Linear examples show that nonlinearity is not necessary; margins and allowed changes determine linear sign stability. Sample-complexity gaps depend on the data model, not a universal exponential rule. Useful features can be non-robust under a chosen perturbation set without being meaningless noise, and robustness is not a synonym for interpretability. OOD detector flags are operational measurements, not a universal proportion or proof of causality. Compare the source assumptions and the exact two-point example in <a href="#s7">section 7</a>.</p>';
function next(entry,html){let s=html;const re=/<section id="s7">[\s\S]*?<\/section>/;assert(re.test(s));s=s.replace(re,section());
 if(entry.file.startsWith('cybersecurity-reworked/')){const intro=/<section id="s2">[\s\S]*?<\/section>/;assert(intro.test(s));s=s.replace(intro,`<section id="s2"><h2>2. Adversarial examples: the vulnerability and the attack</h2>\n${introduction()}\n${why}\n</section>`);}
 else {const first=/<section id="s1">[\s\S]*?<\/section>/,second=/<section id="s2">[\s\S]*?<\/section>/;assert(first.test(s)&&second.test(s));s=s.replace(first,`<section id="s1"><h2>1. Introduction to Adversarial Examples</h2>\n${introduction()}\n</section>`).replace(second,`<section id="s2"><h2>2. Why Adversarial Examples Matter</h2>\n${why}\n</section>`);}
 const q=/<summary>(?:Describe the five hypotheses that explain why adversarial examples exist\. What is the current consensus\?|What do the five perspectives establish, and which conclusions would overstate the evidence\?)<\/summary>\s*<p>[\s\S]*?<\/p>/;assert(q.test(s));return s.replace(q,`<summary>${quizTitle}</summary>\n${quiz}`);
}
if(require.main===module){const file=root+'/cybersecurity/assets/diagrams/cyber-feature-sensitivity.svg',r=plot.render();if(process.argv.includes('--check'))assert.equal(fs.readFileSync(file,'utf8'),r.svg);else fs.writeFileSync(file,r.svg);let patch='*** Begin Patch\n';for(const e of entries){const file=root+'/'+e.file,old=fs.readFileSync(file,'utf8'),s=next(e,old);if(process.argv.includes('--check'))assert.equal(old,s,e.file+' feature content drift');else if(s!==old)patch+='*** Update File: '+file+'\n'+require('./transfer-content.cjs').hunks(old,s);}if(process.argv.includes('--check'))console.log('Shared feature plot, two introductions, five perspective panels and quizzes in sync');else process.stdout.write(patch+'*** End Patch\n');}
module.exports={next,section,introduction,source,panels,quizTitle,model,plot};
