const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process'),m=require('../../cybersecurity/assets/feature-model.cjs');
const close=(a,b)=>assert(Math.abs(a-b)<1e-10,`${a} != ${b}`);let boxes=0,modelCases=0;
for(const eta of [.02,.05,.1,.2,.4])for(const epsilon of [0,.01,.02,.05,.1,.2,.4,.8]){const r=m.evaluate({eta,epsilon});for(const f of r.features){const clean=r.records.map(t=>m.feature(f.kind,t.p,eta)),mean=clean.reduce((s,x)=>s+x,0)/2;close(mean,0);close(clean.reduce((s,x)=>s+x*x,0)/2,1);let worst=0;for(const point of r.records){const corners=[];for(const du of [-epsilon,epsilon])for(const dv of [-epsilon,epsilon])corners.push(point.y*m.feature(f.kind,{u:point.p.u+du,v:point.p.v+dv},eta));const min=Math.min(...corners);close(min,point.y*m.feature(f.kind,point.q,eta));worst+=min/2;assert.equal(point.truthBefore,point.y);assert.equal(point.truthAfter,point.y);close(Math.max(Math.abs(point.q.u-point.p.u),Math.abs(point.q.v-point.p.v)),epsilon);}close(worst,f.worstCorrelation);}modelCases++;}
for(const wu of [-3,-1,0,1,3])for(const wv of [-2,0,2])for(const bias of [-.7,0,.7])for(const u of [-1,.2,1])for(const v of [-.5,0,.7])for(const y of [-1,1])for(const epsilon of [0,.2,.8]){const values=[];for(const du of [-epsilon,epsilon])for(const dv of [-epsilon,epsilon])values.push(y*(wu*(u+du)+wv*(v+dv)+bias));close(m.minimumSignedScore({u:wu,v:wv},bias,{u,v},y,epsilon),Math.min(...values));boxes++;}
const fixture=m.evaluate();assert.deepEqual(fixture.features.map(f=>f.candidatePredictions),[[-1,1],[1,-1]]);assert.equal(m.sign(0),1);assert.deepEqual(m.evaluate({epsilon:.1}).features[1].candidatePredictions,[1,1]);assert.deepEqual(m.evaluate({epsilon:0}).features[1].candidatePredictions,[-1,1]);
let invalid=0;for(const fn of [()=>m.evaluate({eta:0}),()=>m.evaluate({eta:NaN}),()=>m.evaluate({eta:.5}),()=>m.evaluate({epsilon:-1}),()=>m.evaluate({epsilon:1}),()=>m.evaluate({epsilon:Infinity}),()=>m.feature('bad',{u:1,v:1},.1),()=>m.minimumSignedScore({u:1,v:1},0,{u:1,v:NaN},1,.2),()=>m.minimumSignedScore({u:1,v:1},0,{u:1,v:1},0,.2),()=>m.minimumSignedScore({u:1e300,v:0},0,{u:1e300,v:0},1,.2)]){assert.throws(fn);invalid++;}
for(const options of [null,[],true,1,'options',{eps:.2}]){assert.throws(()=>m.evaluate(options));invalid++;}
assert(Object.isFrozen(m.defaults));
const input={eta:.1,epsilon:.2},saved=JSON.stringify(input);m.evaluate(input);assert.equal(JSON.stringify(input),saved);
const evidence=[];for(const [name,wanted] of [['amich','a472a18e177d1cd18b3578f1f790ad596f2a7eb88381c0389f81215909654935'],['ilyas','81c3715d1e256579071591f3bc61f55d63b32a33dcc981026209d14d32990f32']]){const file=process.env[name==='amich'?'NOTES_AMICH_PDF':'NOTES_ILYAS_PDF'];assert(file,'Provide reviewed '+name+' PDF');const sha=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');assert.equal(sha,wanted);const result=spawnSync('pdftotext',['-raw',file,'-'],{encoding:'utf8',timeout:15000,maxBuffer:3e6});assert.equal(result.status,0);const text=result.stdout.replace(/\s+/g,' ');if(name==='amich'){assert.match(text,/CIFAR10.*?90%.*?FGSM.*?87%.*?PGD/);assert.match(text,/SSD.*?Out-of-Distribution Detector/);assert.match(text,/RR ≈ 75%/);}else{assert.match(text,/mean-zero and unit-variance/);assert.match(text,/do not preclude the possibility/);}evidence.push({name,sha256:sha});}
fs.writeFileSync('/home/ybc/notes-legacy-review-artifacts/feature-test.json',JSON.stringify({modelCases,linearCornerChecks:boxes,invalid,fixture,evidence,scope:'Exact two-point example and linear-box identities, not empirical neural-network attacks or an OOD detector'},null,2)+'\n');
console.log(`${modelCases} normalized-feature cases; ${boxes} linear-box corner checks; ${invalid} invalid inputs; default/tie/zero cases and primary-source checks passed`);
