const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process'),c=require('./impact-content.cjs');
const dir=process.env.NOTES_IMPACT_EVIDENCE;assert(dir,'Set NOTES_IMPACT_EVIDENCE to the reviewed PDF/HTML directory');
const pins={eykholt:'fe6aba8e6913df2edc62061d686c87b103e2d65f68de4c38fe014272773e88d0',carlini:'ef9346eb0f143fb73f62161a82e2ae985c3a92eeae0566bb92a19e0335481abc',zhu:'7ffe5a6e22a41591db02c1bebfe842a28b0a645376652b3a461fc38c89fcf0d4',chen:'c6e5b6206654d52fb42923ad904c4039a855b364c4efe79f3e61f9ff05f2d9c7'};
const evidence={};for(const [name,sha] of Object.entries(pins)){const file=path.join(dir,name+'.pdf');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),sha);evidence[name]=execFileSync('pdftotext',['-raw',file,'-'],{encoding:'utf8',maxBuffer:5e6}).replace(/\s+/g,' ');}
assert.match(evidence.eykholt,/LISA-CNN/);assert.match(evidence.eykholt,/Camouflage abstract art 84\.8%/);assert.match(evidence.eykholt,/k = 10, and crop the sign/);
assert.match(evidence.carlini,/do not remain adversarial after being played over-the-air/);assert.match(evidence.carlini,/Are audio adversarial examples transferable\?/);
assert.match(evidence.zhu,/Wenjun Zhu/);assert.match(evidence.zhu,/triggered by acoustic signals/);assert.match(evidence.zhu,/AI component level rather than the AV system level/);
assert.match(evidence.chen,/conceptual scheme/);assert.match(evidence.chen,/simulat/i);assert(!/school bus|military convoy/i.test(evidence.chen),'Re-review changed source claims');
assert.equal(c.data.rows.length,8);assert.equal(new Set(c.data.rows.map(r=>r.id)).size,8);for(const r of c.data.rows){assert(r.observed&&r.limit&&r.refs.length);for(const key of r.refs)assert(c.data.sources[key]?.startsWith('https://'));}
const road=c.data.rows.find(r=>r.id==='road'),speech=c.data.rows.find(r=>r.id==='speech'),malware=c.data.rows.find(r=>r.id==='malware');assert.match(road.observed,/sampled, cropped frames/);assert.match(road.limit,/not a crash rate/);assert.match(speech.observed,/did not remain adversarial/);assert.match(malware.observed,/Android\/DREBIN.*Windows PE/);
(async()=>{const {parse}=await import('../contracts/node_modules/parse5/dist/index.js');const doc=parse(fs.readFileSync(path.join(dir,'ban.html'),'utf8'));function words(n){if(n.nodeName==='script'||n.nodeName==='style')return '';return n.nodeName==='#text'?n.value:(n.childNodes||[]).map(words).join(' ');}const ban=words(doc).replace(/\s+/g,' ');assert.match(ban,/Younghoon Ban/);assert.match(ban,/PE binaries/);assert.match(ban,/65\.6%/);assert.match(ban,/99%/);
const root=path.resolve(__dirname,'../..');for(const e of require('./transfer-sources.cjs')){const html=fs.readFileSync(root+'/'+e.file,'utf8');assert.equal(c.next(e,html,c.dimensions()),html);const errors=[];parse(html,{onParseError:e=>errors.push(e)});assert.deepEqual(errors,[]);assert(!html.includes('transferable across vehicle models'));assert(!html.includes('Neural networks beat every other approach'));}
fs.writeFileSync('/home/ybc/notes-legacy-review-artifacts/impact-test.json',JSON.stringify({pins,rows:8,sourceChecks:true,markup:true,scope:'Source transcription and evidence boundaries; no malware, physical attacks or medical experiments executed'},null,2)+'\n');console.log('Four pinned papers and Ban HTML checked; eight evidence rows, corrected claims, markup and idempotence passed');})().catch(e=>{console.error(e);process.exitCode=1;});
