const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),entries=require('./transfer-sources.cjs'),data=require('./impact-sources.cjs'),{createRenderer,palette}=require('./render.cjs');
const asset=root+'/cybersecurity/assets/diagrams/'+data.diagram.id+'.svg';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const labels={eykholt:'Eykholt et al., §§4–5',sharif:'Sharif et al., §5.2',medical:'Finlayson et al., §3',grosse:'Grosse et al., §4',ban:'Ban et al. (2024)',carlini:'Carlini & Wagner, §§III and V',chen:'Chen (2022)',gazit:'Gazit et al., v4',zhu:'Zhu et al., TPatch'};
function section(r){const d=data.diagram;return `<section id="s8">
<h2>8. Real-world domains: evidence, system impact and limits</h2>
<p>An attack on a model can create a security risk, but a changed prediction is not automatically a failed application or an observed injury. State the input channel, target, measured outcome and downstream assumptions. The eight headings below preserve the course’s domain overview; they are not eight independent demonstrations of real-world harm.</p>
<figure data-static-diagram="${d.id}" data-impact-diagram style="max-width:100%;margin:1.6rem 0"><div role="region" tabindex="0" aria-label="Model error and system impact: scroll horizontally" style="max-width:100%;overflow-x:auto;background:${palette.paper};border:1px solid ${palette.rule};padding:12px;box-sizing:border-box"><img src="../cybersecurity/assets/diagrams/${d.id}.svg" width="${r.width}" height="${r.height}" alt="Physical and digital input paths reach a model, followed by a separately evaluated application and its controls." style="display:block;width:${r.width}px;max-width:none;height:auto;margin:auto"></div><figcaption>${esc(d.caption)}</figcaption></figure>
<div role="region" tabindex="0" aria-label="Eight application domains and evidence limits: scroll horizontally" style="max-width:100%;overflow-x:auto"><table data-impact-evidence style="min-width:760px;table-layout:fixed;width:100%"><caption>Published studies and what their results do not establish; experiments were not rerun here</caption><colgroup><col style="width:20%"><col style="width:40%"><col style="width:40%"></colgroup><thead><tr><th scope="col">Domain</th><th scope="col">Evidence and source</th><th scope="col">Interpretation limit</th></tr></thead><tbody>
${data.rows.map(row=>`<tr data-domain="${row.id}"><th scope="row">${esc(row.domain)}</th><td><p>${esc(row.observed)}</p><p>${row.refs.map(key=>`<a href="${esc(data.sources[key])}">${esc(labels[key])}</a>`).join('; ')}</p></td><td>${esc(row.limit)}</td></tr>`).join('\n')}
</tbody></table></div>
<h3>Physical feasibility is a separate test</h3>
<p>Printing, lighting, distance, viewpoint, sensing and preprocessing can change a perturbation before classification. Eykholt et al. evaluated selected conditions and sampled/cropped drive-by frames, not a complete autonomous vehicle. Carlini &amp; Wagner explicitly identified over-the-air playback and transferability as open questions for their 2018 audio attack. A universal ranking of “physical attacks are less reliable” does not follow without matched tests and a specified metric.</p>
<h3>Connect the model result to CIA without skipping the application</h3>
<p>An attacker-induced wrong decision may violate the intended integrity of the model service. Confidentiality loss needs evidence of unauthorized disclosure; availability loss needs evidence of denied or degraded service. Physical safety is a system consequence, not a fourth CIA component or an automatic consequence of misclassification. Authentication thresholds, independent checks and human review may change the outcome, but their effectiveness must also be tested.</p>
<div class="callout exam"><span class="callout-label">Exam tip</span><p>For three or four domains, explain the attack surface, the measured model behavior, a plausible downstream risk and the missing evidence needed to establish that risk. Distinguish classifier transfer, survival through a physical channel and end-to-end system impact.</p></div>
<details data-impact-check><summary>Does 84.8% targeted misclassification mean an 84.8% crash probability?</summary><p>No. It is the reported rate for sampled, cropped frames in one LISA-CNN camouflage-art drive-by evaluation. Frames are not independent journeys, and the study did not measure crashes. A driving policy, temporal processing, other sensors and controls lie between a frame prediction and a vehicle outcome.</p></details>
</section>`;}
function dimensions(){const s=fs.readFileSync(asset,'utf8');return {width:Number(s.match(/\bwidth="([\d.]+)"/)[1]),height:Number(s.match(/\bheight="([\d.]+)"/)[1])};}
const intro=`<section id="s1">
<h2>1. The ML system as an asset: two attack surfaces</h2>
<p>A classifier maps inputs to labels; training selects parameters using an objective and data. Neural networks do not universally outperform every other method. When an application relies on a model, protect the model, data and surrounding workflow as assets. Clean test accuracy alone does not establish security under adversarial conditions.</p>
<p>Training-time attacks and inference-time attacks involve different capabilities. For example, poisoning changes the learning process or its data, while an evasion example changes an input presented for prediction. A threat model must specify the adversary’s access, objective and constraints; a vulnerability and an attempted attack are not the same as a successful system compromise.</p>
<div class="callout idea"><span class="callout-label">Connection to Module 1</span><p>Assess the CIA properties of the actual service. An unwanted manipulated decision can affect integrity. Availability requires denied or degraded service, and confidentiality requires unauthorized disclosure. Neither follows automatically from every classification error. Safety consequences require a separate system-level analysis, illustrated in <a href="#s8">section 8</a>.</p></div>
<p>Controls address different threats: input robustness, access restrictions, isolation and privacy mechanisms are not interchangeable guarantees. Evaluate the relevant component and then the application, including how it uses model output.</p>
</section>`;
function next(e,html,r){const re=/<section id="s8">[\s\S]*?<\/section>/;assert(re.test(html));let s=html.replace(re,section(r)).replace(/(<a href="#s8">)[^<]*(<\/a>)/,'$1Real-world domains: evidence and impact$2');if(e.file.startsWith('cybersecurity-reworked/')){s=s.replace(/<section id="s1">[\s\S]*?<\/section>/,intro);const q=/(<summary>Which CIA property does each Module-2 attack primarily break\?<\/summary>\s*)<p>[\s\S]*?<\/p>/;assert(q.test(s));s=s.replace(q,(_,head)=>head+'<p>Classify the intended violation and then check whether it occurred. Evasion can affect decision integrity; availability loss requires denied or degraded service, not merely a wrong label. Membership inference, inversion and extraction concern privacy, but a particular attempt does not automatically disclose confidential data. Prompt injection targets instruction integrity and may seek unauthorized disclosure or actions; actual exfiltration violates confidentiality. Separate these objectives from measured application outcomes, as in <a href="#s8">section 8</a>.</p>');}return s;}
if(require.main===module)(async()=>{const renderer=await createRenderer();let r;try{r=await renderer.render(data.diagram);if(process.argv.includes('--check'))assert.equal(fs.readFileSync(asset,'utf8'),r.svg+'\n');else fs.writeFileSync(asset,r.svg+'\n');}finally{await renderer.close();}let patch='*** Begin Patch\n';for(const e of entries){const file=root+'/'+e.file,old=fs.readFileSync(file,'utf8'),s=next(e,old,r);if(process.argv.includes('--check'))assert.equal(old,s,e.file+' impact drift');else if(old!==s)patch+='*** Update File: '+file+'\n'+require('./transfer-content.cjs').hunks(old,s);}if(process.argv.includes('--check'))console.log('Shared impact diagram, eight evidence rows, section check and TOC in sync');else process.stdout.write(patch+'*** End Patch\n');})().catch(e=>{console.error(e);process.exitCode=1;});
module.exports={data,asset,section,next,dimensions};
