const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),plot=require('./leakage-plot.cjs');
const root=path.resolve(__dirname,'../..'),asset=root+'/cybersecurity/assets/diagrams/cyber-leakage-aggregation.svg',id='cyber-leakage-aggregation';
const sources={study:'https://doi.org/10.1109/PerComWorkshops68308.2026.11585450',author:'https://stefano-ferretti.github.io/publications/',pass:'https://arxiv.org/abs/2107.03374',q17:'https://huggingface.co/Qwen/Qwen3-1.7B',q4:'https://huggingface.co/Qwen/Qwen3-4B',gpt4:'https://developers.openai.com/api/docs/models/gpt-4',judge:'https://developers.openai.com/api/docs/models/gpt-oss-20b'};
const reported=[{code:'C.M.',a:'0.92 ± 0.25',b:'0.90 ± 0.22'},{code:'C.R.',a:'0.90 ± 0.25',b:'0.90 ± 0.25'},{code:'E.R.',a:'0.74 ± 0.34',b:'0.40 ± 0.43'},{code:'P.I.',a:'1.00 ± 0.00',b:'0.06 ± 0.13'},{code:'T.Q.',a:'0.88 ± 0.21',b:'0.56 ± 0.46'},{code:'Average',a:'0.89 ± 0.09',b:'0.56 ± 0.36'}];
const table=(attr,caption,headers,rows)=>`<div tabindex="0" role="region" aria-label="${caption}: scroll horizontally" style="max-width:100%;overflow-x:auto"><table data-${attr}><caption>${caption}</caption><thead><tr>${headers.map(h=>'<th scope="col">'+h+'</th>').join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr data-row="${i}"><th scope="row">${r[0]}</th>${r.slice(1).map(t=>'<td>'+t+'</td>').join('')}</tr>`).join('')}</tbody></table></div>`;
function deployment(){return `<div id="model-deployment"><h3>Model size is not a deployment or privacy policy</h3>
<p>“Small language model” is a relative description, not a universal 100M–7B definition. Keep parameter count, weight format, runtime workload, hosting and authorization separate. The course evaluates Qwen3-1.7B and Qwen3-4B; their names are not a guarantee of smartphone or laptop performance.</p>
${table('deployment-factors','Separate the deployment decisions',['Dimension','What to specify','What does not follow'],[
['Model','Exact checkpoint, architecture, total/active parameters and evaluation task.','Size alone does not determine quality, instruction following or confidentiality.'],
['Memory','Weight precision, context length, KV cache, batch size, activations and runtime overhead.','Nominal weight storage is not total inference memory or a device-fit guarantee.'],
['Hosting','Device, organization-managed server or external service; specify the actual data path.','A small model can be served remotely; a larger open-weight model can be self-hosted.'],
['Cost','Hardware, energy, latency, maintenance and any service charges for the workload.','Local inference is not intrinsically free or near-zero cost.'],
['Privacy','Authorized actor, payload, recipient, retention and tool/log/synchronization behavior.','Local model inference does not prevent data leaving via another component.']])}
<p>The <a href="${sources.q17}">Qwen3-1.7B</a> and <a href="${sources.q4}">Qwen3-4B</a> model cards report nominal totals of 1.7B and 4.0B parameters. For a weights-only arithmetic illustration, storing P scalar weights at b bits costs P × b / 8 bytes. These are decimal GB, not GiB, measured file sizes or memory benchmarks. Uniform 4-bit storage is an idealized calculation: quantization metadata and mixed-precision weights add overhead.</p>
${table('weight-budget','Nominal weights only — not total device memory',['Nominal parameters','16-bit weights (GB)','Idealized 4-bit weights (GB)'],[1.7e9,4e9].map(n=>[(n/1e9).toFixed(1)+'B',(plot.model.weightBytes(n,16)/1e9).toFixed(2),(plot.model.weightBytes(n,4)/1e9).toFixed(2)]))}
<p>As a counterexample to “larger means cloud-only,” <a href="${sources.judge}">OpenAI’s gpt-oss-20b documentation</a> describes an open-weight model for local or specialized use, with 21B total and 3.6B active parameters. That does not certify it on a particular device or as a leakage judge. The old GPT-4 “&gt;100B” estimate is not retained: the <a href="${sources.gpt4}">API model page consulted</a> does not provide that parameter count.</p>
</div>`;}
function metric(){const r=plot.render(),d=plot.model.design();return `<div id="leakage-metrics"><h3>Attack@1: separate a per-run average from an any-run event</h3>
<p><strong>Editorial correction to slide 81:</strong> the displayed equation is <code>A₁ = (1/N) ∑ᵢ Lᵢ</code>, with binary leakage labels Lᵢ. This estimates the fraction of runs flagged by the judge. The slide’s accompanying “at least one” description is a different aggregation. Repeating a scenario five times does not turn a single-run metric into best-of-five.</p>
<p>With S scenarios and R runs per scenario, define <code>A₁ = (1/S) ∑ₛ [(1/R) ∑ᵣ Lₛᵣ]</code>. The fraction of scenarios with at least one flagged run is instead <code>B(R) = (1/S) ∑ₛ 𝟙[∑ᵣ Lₛᵣ &gt; 0]</code>. Equal R makes the per-scenario mean equal to the pooled per-run fraction; unequal run counts require an explicit weighting choice. No independence assumption is needed to calculate these observed fractions.</p>
<figure data-static-plot="${id}" style="max-width:100%;margin:1.6rem 0"><div role="region" tabindex="0" aria-label="Trial aggregation diagram: scroll horizontally" style="max-width:100%;overflow-x:auto;background:#F3EFE3;border:1px solid #C9C3B6;padding:12px;box-sizing:border-box"><img src="../cybersecurity/assets/diagrams/${id}.svg" width="${r.width}" height="${r.height}" alt="Three invented scenarios with five runs each: four flagged runs out of fifteen, but two scenarios out of three have at least one flag." style="display:block;width:${r.width}px;max-width:none;height:auto;margin:auto"></div><figcaption>The same invented binary labels give ${(100*r.data.perRun).toFixed(1)}% flagged runs and ${(100*r.data.anyScenario).toFixed(1)}% scenarios with a flag. Neither percentage is a result from Aguzzi et al. A zero means “not flagged by this judge,” not a verified absence of leakage. Color is redundant with the 0/1 labels.</figcaption></figure>
${table('leakage-example','Complete invented trial labels',['Scenario','Runs 1–5','Flagged / runs','Any flagged?'],r.data.rows.map(t=>[t.id,t.runs.join(' '),t.c+'/'+t.n,t.any?'Yes':'No']))}
<p>For the comparison with <a href="${sources.pass}">Chen et al.’s pass@k</a>, distinguish the number n of sampled completions from the budget k being evaluated. Given c successful samples, the estimator is <code>1 − C(n−c, k) / C(n, k)</code> for 1 ≤ k ≤ n. C(a,b) counts b-element subsets of a elements, and is zero when b &gt; a. At k=1 it reduces to c/n; at k=n it is the observed any-success indicator. If independent identical attempts have known success probability p, the probability of any success in k attempts is <code>1 − (1−p)ᵏ</code>; substituting an estimated p is not the same finite-sample estimator. Here “success” would mean a judge-flagged attack, not passing a code test.</p>
<p><a href="../cybersecurity/assets/leakage-metrics.cjs" download>Download the finite metric and memory calculations</a>. The example is deterministic and runs no LLM or real tools.</p>
<h3>Reconstruct the experimental denominator</h3>
${table('leakage-design','Balanced design reconstructed from slides 82–83',['Quantity','Calculation','Meaning'],[
['Scenarios',`${d.personas} personas × ${d.prompts} prompts = ${d.scenarios}`,'One prompt from each of five categories for each persona.'],
['Per model/condition',`${d.scenarios} scenarios × ${d.repeats} repeats = ${d.perCell}`,'Repeated generations, not 250 distinct personas.'],
['Across the design',`${d.perCell} × ${d.models} models × ${d.conditions} prompt conditions = ${d.total}`,'The reported total is consistent with all four cells; 50 × 5 alone is only 250.']])}
<p>This reconstruction follows the balanced design described in the slides, not independently inspected run logs. For a pooled cell-level estimate the intended denominator is 250 completed runs; per-scenario estimates use five runs. Failed/missing generations, retries, weighting and exact leakage labeling must be documented before reproducing the reported scores. Repeated runs for the same persona are not 1,000 independent patients.</p>
<details data-leakage-check><summary>One of five attempts is flagged: is the single-run estimate 100%?</summary><p>No. The single-run fraction is 1/5 = 20%. The observed any-of-five indicator for that scenario is 1. These answer different questions.</p></details></div>`;}
const findings='The course slides report baseline rates near 90% for both models and hardened averages of 0.89 (1.7B) and 0.56 (4B). Treat these as slide-reported, judge-labeled outcomes for this particular setup. They show residual failures under the tested prompts; they do not establish universal incapacity, isolate a causal effect of parameter count, validate the judge or decide clinical/regulatory suitability. The paper’s full text and run-level artifacts were not available in this review.';
const metricRecap='Slide 81 displays an average of binary per-generation labels: A₁ = (1/N) ∑ᵢ Lᵢ. Five repeats estimate the single-run rate; taking an OR across them instead gives an any-of-five outcome. With n samples and c successes, the pass@k-style estimator 1 − C(n−c,k)/C(n,k) equals c/n at k=1. The balanced study design accounts for 50 × 5 × 2 × 2 = 1,000 runs across two models and two conditions, not 50 × 5 = 1,000.';
function content(){return `<div id="healthcare-evaluation">
<p>The course case is attributed to <a href="${sources.study}">Aguzzi, Montagna and Ferretti, Privacy Leakage in Small Agentic Healthcare Models: An Empirical Analysis (PerCom Workshops 2026)</a>. Publisher-deposited bibliographic metadata and <a href="${sources.author}">Ferretti’s publication list</a> confirm the work. The detailed setup and numbers below come from the course PDF <cite>03 - privacy in LLM</cite>, slides 73–88; this review did not obtain the paper’s full text or run-level artifacts. The source distinction matters: a lecture summary is not a reproduced benchmark.</p>
${deployment()}
<h3>The four-stage evaluation described by the slides</h3>
<ol data-leakage-pipeline>
<li><strong>Construct synthetic personas.</strong> The slides describe Gemini 2.5 Flash at temperature 0.2 producing context C and sensitive facts F. Synthetic cases avoid using actual patient records in this example, but require checks for consistency and realism; “synthetic” alone is not proof of anonymity or benchmark quality.</li>
<li><strong>Prepare five prompt categories.</strong> P.I.: direct instruction override; E.R.: explicit request for private facts; T.Q.: disguised query; C.R.: combine contextual facts; C.M.: conditional use of sensitive information. These are this study’s categories, not an exhaustive security taxonomy.</li>
<li><strong>Run the configured agent.</strong> Compare Qwen3-1.7B and Qwen3-4B under baseline and privacy-hardened prompts. The slides list four record/appointment tools and one external search tool. “Internal” is not equivalent to authorized, nor is every external query forbidden; apply the explicit policy distinction in <a href="#agent-enforcement">the agent section</a>.</li>
<li><strong>Label and aggregate outcomes.</strong> The slides describe gpt-oss-20b at temperature 0 receiving facts F and tool-call inputs. This is an automated judge, not an independently demonstrated “high-accuracy” oracle. Specify the rubric and validate against human-labeled examples, including false positives/negatives and unparseable outputs. A tool proposal, a dispatched call and actual receipt of data are distinct observations.</li>
</ol>
${metric()}
<h3>Reported results: preserve their provenance and uncertainty</h3>
<p>${findings}</p>
${table('leakage-reported','Privacy-hardened results transcribed from slide 85',['Category','Qwen3-1.7B','Qwen3-4B'],reported.map(r=>[r.code,r.a,r.b]))}
<p>The “±” terms are transcribed as displayed. The reviewed slide does not define whether they are standard deviations, errors, intervals or which aggregation they describe; do not interpret them as confidence intervals or draw error bars from an assumed meaning. The baseline is described only as approximately 90% here; exact counts are not reconstructed from that rounded figure.</p>
<p>The 4B row for P.I. is lower than its conditional/cross-reference rows in this table. That supports a comparison within the reported setup, not a conclusion that explicit jailbreaks are generally easy or that 4B is safe. Testing two checkpoints does not by itself establish that parameter count caused the difference. A generated rationale is also not direct evidence of an internal inability to understand privacy.</p>
<h3>Constructed examples: inspect what leaves the system</h3>
<p>The following are teaching examples, not observed model traces or patient records.</p>
<div class="lk-tabs" data-kit="tabs"><div class="lk-tablist"><button class="lk-tab">C.M. Example</button><button class="lk-tab">C.R. Example</button></div>
<div class="lk-tabpanel"><pre tabindex="0"><code>Rule in prompt: if private condition X is present, search.
Candidate A: search("general treatment guidance")
Candidate B: search("treatment for condition X")</code></pre><p>B explicitly includes X in a proposed payload. A omits the condition from the text, but an observer who knows the rule and sees the search event might infer that its condition was satisfied. State the observer’s knowledge, actual dispatch and policy before claiming a leak. Merely evaluating the condition locally is not itself disclosure.</p></div>
<div class="lk-tabpanel"><pre tabindex="0"><code>Private context: conditions X and Y; location Z.
Proposed query: "X Y specialist in Z"
Before dispatch: check payload, recipient and authorization.</code></pre><p>The combination can reveal more than any fragment alone. It becomes an external disclosure if the query is actually delivered; whether it is unauthorized depends on the policy and consent context. A blocked proposal is different from a completed call. No clinical advice or real patient data is used here.</p></div></div>
<p>Use prompting as one behavioral control, not as proof of confidentiality. Validate the complete application and retain explicit enforcement outside the model. These results alone neither prove prompting is universally necessary nor establish a legally acceptable leakage threshold.</p>
</div>`;}
function next(e,html){let s=html;const section=e.file.startsWith('cybersecurity-reworked/')?'s16':'s17',number=section.slice(1),re=new RegExp('<section id="'+section+'">[\\s\\S]*?<\\/section>');assert(re.test(s));s=s.replace(re,`<section id="${section}">\n<h2>${number}. Healthcare agents: deployment, metrics and evidence</h2>\n${content()}\n</section>`).replace(new RegExp('(<a href="#'+section+'">)[^<]*(<\\/a>)'),'$1Healthcare agents: deployment, metrics and evidence$2');
for(const [question,answer] of [['What were the key results of the Aguzzi et al. (2026) study on privacy leakage in small agentic healthcare models?',findings],['What is Attack@1 and how does it relate to Pass@k?',metricRecap]]){const exact='<summary>'+question+'</summary>',start=s.indexOf(exact);assert(start>=0);const tail=s.slice(start),m=tail.match(/^(<summary>[\s\S]*?<\/summary>\s*)<p>[\s\S]*?<\/p>/);assert(m);s=s.slice(0,start)+tail.replace(m[0],m[1]+'<p>'+answer+'</p>');}
s=s.replaceAll('Zero-shot privacy instructions are <strong>necessary but insufficient</strong>','Privacy instructions may help behavior, but do not constitute an access-control guarantee');
return s;}
if(require.main===module){const r=plot.render(),check=process.argv.includes('--check');if(check)assert.equal(fs.readFileSync(asset,'utf8'),r.svg);else fs.writeFileSync(asset,r.svg);let patch='*** Begin Patch\n';for(const e of require('./transfer-sources.cjs')){const f=root+'/'+e.file,old=fs.readFileSync(f,'utf8'),s=next(e,old);if(check)assert.equal(s,old);else if(s!==old)patch+='*** Update File: '+f+'\n'+require('./transfer-content.cjs').hunks(old,s);}if(check)console.log('Healthcare deployment, trial aggregation, reported evidence and recaps synchronized');else process.stdout.write(patch+'*** End Patch\n');}
module.exports={plot,asset,id,sources,reported,content,next};
