const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process'),c=require('./leakage-content.cjs'),m=c.plot.model;
const root=path.resolve(__dirname,'../..'),out='/home/ybc/notes-legacy-review-artifacts',dir=process.env.NOTES_HEALTHCARE_EVIDENCE;assert(dir,'Set NOTES_HEALTHCARE_EVIDENCE to the reviewed evidence directory');
const pins={'code.pdf':'ebae72ea0e8a5eb2ecbccdb985aec6cc1254a7c4d29e6d4de7866db1e66c4855','gpt-4.md':'0e29ac3ec226f710b855fc58708cabc7084b0a7db14efaa129fb1540b60ba31a','gpt-oss.md':'bf93768d75201d21fbff202ad3a7f6e331e60fe74170957f265aada7a39366a0','qwen17.md':'257e52c419dac2258852643f18af6c974f21f8c6c1b6f371b6cca6201cf29091','qwen4.md':'71add1cd091c309b1cb1a6b943f2476eb2b004124b3bd1d32dcd0b24cc1abc47'};
for(const [file,sha] of Object.entries(pins))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,file))).digest('hex'),sha);
const slides='/home/ybc/content/exams/Cybersecurity/03 - privacy in LLM.pdf';assert.equal(crypto.createHash('sha256').update(fs.readFileSync(slides)).digest('hex'),'82506e353bda60ff819a96eaa8b538818b625639343b658e434b2bf6a6855749');
const evidence=execFileSync('pdftotext',['-raw',dir+'/code.pdf','-'],{encoding:'utf8',maxBuffer:5e6}).replace(/\s+/g,' ');assert.match(evidence,/unbiased estimator/);assert.match(evidence,/n ≥ k samples per task/);assert.match(evidence,/count the number of correct samples/);
assert.match(fs.readFileSync(dir+'/qwen17.md','utf8'),/Number of Parameters: 1.7B/);assert.match(fs.readFileSync(dir+'/qwen4.md','utf8'),/Number of Parameters: 4.0B/);assert.match(fs.readFileSync(dir+'/gpt-oss.md','utf8'),/21B parameters with 3.6B active parameters/);assert(!fs.readFileSync(dir+'/gpt-4.md','utf8').includes('100B'));
const bib=JSON.parse(fs.readFileSync(dir+'/crossref.json','utf8')).message;assert.equal(bib.DOI,'10.1109/percomworkshops68308.2026.11585450');assert.equal(bib.title[0],'Privacy Leakage in Small Agentic Healthcare Models: An Empirical Analysis');assert.deepEqual(bib.author.map(a=>a.family),['Aguzzi','Montagna','Ferretti']);assert.equal(bib.publisher,'IEEE');assert.equal(bib['published-print']['date-parts'][0][0],2026);
let labelSets=0,subsets=0,estimates=0;for(let n=1;n<=8;n++){for(let mask=0;mask<2**n;mask++){const bits=Array.from({length:n},(_,i)=>(mask>>i)&1),count=bits.filter(Boolean).length,r=m.analyze([{id:'A',runs:bits}]);assert.equal(r.leaks,count);assert.equal(r.perRun,count/n);assert.equal(r.anyScenario,Number(mask>0));labelSets++;}
 for(let count=0;count<=n;count++)for(let k=1;k<=n;k++){let all=0,hits=0;for(let mask=1;mask<2**n;mask++){const positions=Array.from({length:n},(_,i)=>i).filter(i=>(mask>>i)&1);if(positions.length!==k)continue;all++;hits+=Number(positions.some(i=>i<count));subsets++;}assert(Math.abs(m.anyOfK(n,count,k)-hits/all)<1e-12);estimates++;}}
const r=m.analyze(m.example());assert.equal(r.perRun,4/15);assert.equal(r.anyScenario,2/3);assert.equal(r.scenarioMean,(.2+0+.6)/3);
function exactChoose(n,k){if(k>n)return 0n;let r=1n;for(let i=1;i<=k;i++)r=r*BigInt(n-i+1)/BigInt(i);return r;}
let boundaryEstimates=0;for(let n=1;n<=20;n++)for(let count=0;count<=n;count++)for(let k=1;k<=n;k++){const expected=1-Number(exactChoose(n-count,k))/Number(exactChoose(n,k));assert(Math.abs(m.anyOfK(n,count,k)-expected)<1e-12);boundaryEstimates++;}
const maximal=m.analyze(Array.from({length:20},(_,i)=>({id:'S'+i,runs:Array.from({length:20},(_,j)=>Number(j<i))})));assert.equal(maximal.total,400);assert.equal(maximal.leaks,190);assert.equal(maximal.any,19);
const concentrated=m.analyze([{id:'A',runs:[1,1,1,1,0]},{id:'B',runs:[0,0,0,0,0]},{id:'C',runs:[0,0,0,0,0]}]),distributed=m.analyze([{id:'A',runs:[1,1,0,0,0]},{id:'B',runs:[1,0,0,0,0]},{id:'C',runs:[1,0,0,0,0]}]);assert.equal(concentrated.perRun,distributed.perRun);assert.equal(concentrated.anyScenario,1/3);assert.equal(distributed.anyScenario,1);
const unequal=m.analyze([{id:'A',runs:[1]},{id:'B',runs:[0,0,0,0,0]}]);assert.equal(unequal.perRun,1/6);assert.equal(unequal.scenarioMean,.5);assert.equal(unequal.equalRuns,false);
const initial=m.example(),saved=JSON.stringify(initial);m.analyze(initial).rows[0].runs[0]=0;assert.equal(JSON.stringify(initial),saved);
assert.throws(()=>m.analyze(new Array(3)),TypeError,'Missing scenarios must not silently become NaN aggregates');
assert.deepEqual(m.design(),{personas:10,prompts:5,repeats:5,models:2,conditions:2,scenarios:50,perCell:250,total:1000});let designs=0;for(const personas of [1,10,100])for(const prompts of [1,5])for(const repeats of [1,5])for(const models of [1,2])for(const conditions of [1,2]){const d=m.design({personas,prompts,repeats,models,conditions});assert.equal(BigInt(d.total),BigInt(personas)*BigInt(prompts)*BigInt(repeats)*BigInt(models)*BigInt(conditions));designs++;}
for(const p of [1.7e9,4e9])for(const b of [4,8,16,32])assert.equal(BigInt(m.weightBytes(p,b)),BigInt(p)*BigInt(b)/8n);
const invalid=[()=>m.analyze([]),()=>m.analyze(null),()=>m.analyze([{id:'A',runs:[]}]),()=>m.analyze([{id:'A',runs:[2]}]),()=>m.analyze([{id:'A',runs:[true]}]),()=>m.analyze([{id:'A',runs:new Array(5)}]),()=>m.analyze([{id:'A',runs:[1],extra:1}]),()=>m.analyze([{id:'A',runs:[1]},{id:'A',runs:[0]}]),()=>m.anyOfK(0,0,1),()=>m.anyOfK(21,1,1),()=>m.anyOfK(5,6,1),()=>m.anyOfK(5,1,6),()=>m.anyOfK(5,1,0),()=>m.weightBytes(1.5,16),()=>m.weightBytes(10,3),()=>m.design({repeats:0}),()=>m.design({models:Infinity}),()=>m.design({personas:1001})];for(const fn of invalid)assert.throws(fn,TypeError);
assert.deepEqual(c.reported.map(r=>[r.code,r.a,r.b]),[['C.M.','0.92 ± 0.25','0.90 ± 0.22'],['C.R.','0.90 ± 0.25','0.90 ± 0.25'],['E.R.','0.74 ± 0.34','0.40 ± 0.43'],['P.I.','1.00 ± 0.00','0.06 ± 0.13'],['T.Q.','0.88 ± 0.21','0.56 ± 0.46'],['Average','0.89 ± 0.09','0.56 ± 0.36']]);
(async()=>{const {parse}=await import('../contracts/node_modules/parse5/dist/index.js');for(const e of require('./transfer-sources.cjs')){const html=fs.readFileSync(root+'/'+e.file,'utf8'),errors=[];parse(html,{onParseError:e=>errors.push(e)});assert.deepEqual(errors,[]);assert.equal(c.next(e,html),html);const old=execFileSync('git',['show','7e2a3ce:'+e.file],{cwd:root,encoding:'utf8'});for(const marker of ['data-kit="tabs"','data-kit="state-explorer"','data-fgsm','<script','data-agent-case='])assert.equal(html.split(marker).length,old.split(marker).length,'Preserve '+marker);
for(const wrong of ['<td>Near-zero</td>','<td>&gt;100B</td>','lacking capacity to enforce complex negative constraints','checking if any run resulted in leakage','there are <strong>no built-in privacy mechanisms</strong>'])assert(!html.includes(wrong),wrong);
assert.match(html,/did not obtain the paper’s full text or run-level artifacts/);assert.match(html,/do not interpret them as confidence intervals/);}
assert.equal(fs.readFileSync(c.asset,'utf8'),c.plot.render().svg);fs.writeFileSync(out+'/leakage-test.json',JSON.stringify({pins,slideSha:'82506e353bda60ff819a96eaa8b538818b625639343b658e434b2bf6a6855749',labelSets,subsets,estimates,boundaryEstimates,designs,weights:8,invalid:invalid.length,reportedRows:6,markup:true,idempotence:true,scope:'Finite calculations and slide transcription; healthcare full text and raw outcomes not obtained'},null,2)+'\n');console.log(`${labelSets} label sets, ${estimates} estimators/${subsets} subsets, ${boundaryEstimates} BigInt checks, ${designs} designs, 8 memory budgets, ${invalid.length} invalids, pinned sources, slide table and markup passed`);})().catch(e=>{console.error(e);process.exitCode=1;});
