const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{build,arrivals,units,transfer}=require('../../ds/assets/ledger-fork.js'),{Model}=require('../../ds/assets/pow-trials.js');
const file=path.resolve(__dirname,'../../ds/DS-C4.html'),esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function chainMarkup(){const blocks=build();return '<!-- BEGIN LEDGER TRACE -->\n<details data-ledger-trace><summary>Every arrival and the selected branch</summary><p>All balances use toy units. Work is equal per non-genesis block. A tie retains the first-seen tip in this example. Scroll horizontally on narrow screens.</p><div role="region" tabindex="0" aria-label="Ledger arrivals, horizontally scrollable" style="max-width:100%;overflow-x:auto"><table style="width:100%;min-width:660px;table-layout:fixed"><thead><tr><th scope="col">Received</th><th scope="col">Tip</th><th scope="col">Alice</th><th scope="col">Bob</th><th scope="col">Carol</th><th scope="col">Eve</th></tr></thead><tbody>\n'+arrivals(blocks).map(s=>'<tr><th scope="row">'+s.arrived.toUpperCase()+'</th><td>'+s.tip.toUpperCase()+'</td>'+Object.values(s.state).map(v=>'<td>'+units(v)+'</td>').join('')+'</tr>').join('\n')+'\n</tbody></table></div></details>\n'+blocks.map(b=>'<details data-ledger-block="'+b.id+'"><summary>'+b.id.toUpperCase()+': parent '+(b.parent?.toUpperCase()||'none')+', height '+b.height+'</summary><p>Included: '+esc(b.included.map(transfer).join('; ')||'none')+'. Rejected before inclusion: '+esc(b.rejected.map(transfer).join('; ')||'none')+'.</p><p>Balances: '+Object.entries(b.state).map(([n,v])=>n+'='+units(v)).join(', ')+'.</p></details>').join('\n')+'\n<!-- END LEDGER TRACE -->'}
async function powMarkup(){const m=new Model(),rows=[];while(m.blocks.length<1&&m.attempts<10000)rows.push(await m.step());assert(m.blocks.length===1);return '<!-- BEGIN POW TRACE -->\n<details data-pow-trace><summary>Reproducible SHA-256 trials until the first toy block</summary><p>Difficulty: 4 zero bits. Each full digest is computed from the displayed input format. These fixed outcomes illustrate trials, not empirical hardware probabilities. Scroll horizontally on narrow screens.</p><div role="region" tabindex="0" aria-label="Hash trials, horizontally scrollable" style="max-width:100%;overflow-x:auto"><table style="width:100%;min-width:740px;table-layout:fixed"><thead><tr><th scope="col">Trial / miner / nonce</th><th scope="col" style="width:65%">SHA-256 digest</th><th scope="col">Result</th></tr></thead><tbody>\n'+rows.map(e=>'<tr><th scope="row">'+e.attempt+' / '+e.miner+' / '+e.nonce+'</th><td style="overflow-wrap:anywhere"><code style="white-space:normal">'+e.hash+'</code></td><td>'+(e.success?'valid':'retry')+'</td></tr>').join('\n')+'\n</tbody></table></div></details>\n<!-- END POW TRACE -->'}
async function main(){
 const s=fs.readFileSync(file,'utf8'),pairs=[
  [/<!-- BEGIN LEDGER TRACE -->[\s\S]*?<!-- END LEDGER TRACE -->/,chainMarkup()],
  [/<!-- BEGIN POW TRACE -->[\s\S]*?<!-- END POW TRACE -->/,await powMarkup()]
 ];let patch='';
 for(const [re,next]of pairs){const m=s.match(re);assert(m);if(process.argv.includes('--check'))assert.equal(m[0],next);else patch+='@@\n'+m[0].split('\n').map(l=>'-'+l).join('\n')+'\n'+next.split('\n').map(l=>'+'+l).join('\n')+'\n'}
 if(process.argv.includes('--check'))console.log('Ledger and actual SHA-256 traces in sync');else process.stdout.write('*** Begin Patch\n*** Update File: '+file+'\n'+patch+'*** End Patch\n');
}
if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1});module.exports={chainMarkup,powMarkup};
