const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const fork=require('../../ds/assets/ledger-fork.js'),pow=require('../../ds/assets/pow-trials.js'),{chainMarkup,powMarkup}=require('./ledger-traces.cjs');
const root=path.resolve(__dirname,'../..'),out='/home/ybc/notes-legacy-review-artifacts';
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
async function main(){
 const blocks=fork.build(),arrivals=fork.arrivals(blocks);assert.deepEqual(arrivals.map(x=>x.tip),['g','b1','b2','b3a','b3a','b4']);
 assert.deepEqual(blocks.map(b=>Object.values(b.state)),[[40,10,4,1],[34,16,4,1],[34,14,6,1],[34,15,5,1],[30,14,10,1],[30,14,8,3]]);
 assert.deepEqual(arrivals.at(-1).removed,['b3a']);assert.deepEqual(arrivals.at(-1).added,['b3b','b4']);assert.equal(blocks[2].rejected.length,1);assert.equal(blocks[2].included.length,1);
 // Independently replay each selected ancestor path, not a flat arrival list.
 for(const b of blocks){const state={Alice:40,Bob:10,Carol:4,Eve:1};for(const id of fork.branch(blocks,b.id))for(const t of blocks.find(b=>b.id===id).included){assert(state[t.from]>=t.amount);state[t.from]-=t.amount;state[t.to]+=t.amount}assert.deepEqual(b.state,state);assert.equal(Object.values(state).reduce((a,b)=>a+b),55);assert(Object.values(state).every(v=>Number.isSafeInteger(v)&&v>=0))}
 for(const spec of [[{id:'g',parent:'oops',work:0,proposals:[]}],[{id:'g',parent:null,work:0,proposals:[]},{id:'x',parent:'x',work:1,proposals:[]}],[{id:'g',parent:null,work:0,proposals:[]},{id:'x',parent:'g',work:1,proposals:[{from:'Alice',to:'Bob',amount:-1}]}]])assert.throws(()=>fork.build(spec));
 const synthetic=fork.build([{id:'g',parent:null,work:0,proposals:[]},{id:'a',parent:'g',work:1,proposals:[]},{id:'b',parent:'a',work:1,proposals:[]},{id:'c',parent:'g',work:3,proposals:[]}]);assert.equal(fork.arrivals(synthetic).at(-1).tip,'c','Work, not raw height (abstract fixture, not Bitcoin retargeting)');
 assert.deepEqual(Object.fromEntries(['A','B','C','D'].map(n=>[n,pow.schedule.filter(x=>x===n).length])),{A:7,B:6,C:5,D:2});assert.equal(await pow.hash('abc'),sha('abc'));
 for(let bits=1;bits<=12;bits++){const limit=1n<<BigInt(256-bits),hex=n=>n.toString(16).padStart(64,'0');assert(pow.valid(hex(limit-1n),bits));assert(!pow.valid(hex(limit),bits))}
 for(const value of ['','g'.repeat(64),'0'.repeat(63)])assert.throws(()=>pow.valid(value,4));assert.throws(()=>new pow.Model(5));
 let trials=0;const examples={};for(const bits of [4,8,12]){const m=new pow.Model(bits),nonces={A:0,B:0,C:0,D:0};let previous='0'.repeat(64),height=1;const seen=new Set();while(m.blocks.length<3&&m.attempts<50000){const e=await m.step();trials++;assert.equal(e.hash,sha(e.input));assert(!seen.has(e.input));seen.add(e.input);assert.deepEqual(JSON.parse(e.input),['notes-pow-v1',height,previous,e.miner,nonces[e.miner],bits]);assert.equal(e.success,e.hash.startsWith('0'.repeat(bits/4)));nonces[e.miner]++;if(e.success){previous=e.hash;height++;for(const k of Object.keys(nonces))nonces[k]=0}assert.equal(m.attempts,Object.values(m.counts).reduce((a,b)=>a+b));assert.equal(m.blocks.length,Object.values(m.wins).reduce((a,b)=>a+b))}assert.equal(m.blocks.length,3);examples[bits]={attempts:m.attempts,blocks:m.blocks.map(e=>({attempt:e.attempt,miner:e.miner,hash:e.hash}))}}
 const m=new pow.Model(),pending=m.step();await assert.rejects(()=>m.step());const checkpoint=m.clone();await pending;assert.equal(checkpoint.attempts,0);await checkpoint.step();assert.equal(checkpoint.attempts,1);assert.equal(m.attempts,1);const snap=m.snapshot();snap.counts.A=999;assert.notEqual(m.counts.A,999);
 const html=fs.readFileSync(root+'/ds/DS-C4.html','utf8');assert(html.includes(chainMarkup()));assert(html.includes(await powMarkup()));console.log(`${trials} actual SHA-256 trials checked with independent Node hash; branch replay, rejected transfer, reorganization, work selection, target boundaries and immutable checkpoint passed`);
 const {chromium}=require('playwright'),b=await chromium.launch(),preview='http://127.0.0.1:8787/',results=[];fs.mkdirSync(out,{recursive:true});async function route(p){await p.route(/^https?:/,r=>r.request().url().startsWith(preview)?r.continue():/mermaid.*\.js/.test(r.request().url())?r.fulfill({path:path.join(path.dirname(require.resolve('mermaid')),'mermaid.min.js')}):/highlight\.min\.js/.test(r.request().url())?r.fulfill({path:root+'/dl/assets/highlight.min.js'}):r.abort())}
 try{for(const width of [1280,390]){const p=await b.newPage({viewport:{width,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await route(p);await p.goto(preview+'ds/DS-C4.html');await p.waitForFunction(()=>document.querySelector('#chain-viz').dataset.ledgerFork==='true');const f=p.locator('#chain-viz');
  for(let i=0;i<arrivals.length;i++){if(i)await f.locator('#fork-next').click();const a=arrivals[i];assert.match(await f.getByRole('status').textContent(),new RegExp('Selected tip: '+a.tip.toUpperCase()));assert.equal(await f.locator('[data-fork-balances]').textContent(),'Active-tip balances: '+Object.entries(a.state).map(([n,v])=>n+'='+v/2).join(', ')+' units.');for(const id of a.known){await f.locator('#fork-block-'+id).click();assert.match(await f.locator('[data-fork-detail]').textContent(),new RegExp(id.toUpperCase()+' · height'));assert.equal(await f.locator('#fork-block-'+id).getAttribute('aria-pressed'),'true')}if(i>=3)await f.screenshot({path:path.join(out,`fork-arrival-${i}-${width}.png`)})}assert(await f.locator('#fork-next').isDisabled());await f.locator('#fork-reset').click();assert.equal(await f.locator('[id^=fork-block-]').count(),1);
  const h=p.locator('#pow-mining-sim'),model=new pow.Model();await h.locator('#pow-step').focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>!document.querySelector('#pow-step').disabled);const first=await model.step();assert.equal(await h.locator('[data-pow-hash]').textContent(),first.hash);
  await h.locator('#pow-reset').click();await h.locator('#pow-auto').click();await p.waitForFunction(()=>!document.querySelector('#pow-step').disabled,{},{timeout:30000});assert.match(await h.getByRole('status').textContent(),/5 toy blocks found/);const expected=new pow.Model();while(expected.blocks.length<5)await expected.step();assert.equal(await h.locator('[data-pow-hash]').textContent(),expected.last.hash);assert.deepEqual(await h.locator('[data-pow-counts] tr').evaluateAll(es=>es.map(e=>[...e.children].map(c=>c.textContent))),['A','B','C','D'].map(n=>[n,String(expected.counts[n]),String(expected.wins[n])]));await h.screenshot({path:path.join(out,`pow-five-${width}.png`)});
  await h.locator('#pow-reset').click();await p.evaluate(()=>{document.querySelector('#pow-auto').click();document.querySelector('#pow-stop').click();document.querySelector('#pow-step').click()});await p.waitForFunction(()=>!document.querySelector('#pow-step').disabled);assert.match(await h.getByRole('status').textContent(),/1 attempts/);assert.equal(await h.locator('[data-pow-hash]').textContent(),first.hash);
  await p.evaluate(()=>{document.querySelector('#pow-auto').click();document.querySelector('#pow-reset').click()});await p.waitForTimeout(100);assert.match(await h.getByRole('status').textContent(),/0 attempts; 0 toy blocks/);await h.locator('#pow-bits').selectOption('8');assert.equal(await p.evaluate(()=>document.activeElement.id),'pow-bits');await h.locator('#pow-step').click();await p.waitForFunction(()=>!document.querySelector('#pow-step').disabled);const eight=new pow.Model(8);assert.equal(await h.locator('[data-pow-hash]').textContent(),(await eight.step()).hash);
  let traceRows=0;for(const selector of ['[data-ledger-trace]','[data-pow-trace]']){const d=p.locator(selector);await d.locator('summary').click();traceRows+=await d.locator('tbody tr').count();const region=d.locator('[role=region]');assert(await d.locator('td,th').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.clientWidth+1)));if(await region.evaluate(e=>e.scrollWidth>e.clientWidth+1)){await region.focus();await p.keyboard.press('ArrowRight');await p.waitForFunction(e=>e.scrollLeft>0,await region.elementHandle())}await d.screenshot({path:path.join(out,`${selector.includes('ledger')?'ledger':'pow'}-trace-${width}.png`)})}
  for(const id of ['ds-ledger-fork','ds-pow-trial']){const fig=p.locator(`[data-static-diagram="${id}"]`);assert(await fig.locator('img').evaluate(i=>i.complete&&i.naturalWidth>0));await fig.screenshot({path:path.join(out,`${id}-${width}.png`)})}
  assert.deepEqual(errors,[]);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));results.push({width,arrivals:6,autoBlocks:5,cancelAndReset:true,traceRows,errors});await p.close();
 }
 const control=await b.newPage();await route(control);await control.goto(preview+'ds/DS-C4.html');await control.evaluate(()=>{crypto.subtle.digest=async()=>new Uint8Array(32).fill(255).buffer});await control.locator('#pow-auto').click();await control.waitForFunction(()=>!document.querySelector('#pow-step').disabled,{},{timeout:30000});assert.match(await control.locator('#pow-mining-sim [role=status]').textContent(),/50000 attempts; 0 toy blocks/);assert.match(await control.locator('#pow-mining-sim [role=status]').textContent(),/Trial limit reached/);await control.locator('#pow-reset').click();await control.evaluate(()=>{crypto.subtle.digest=async()=>{throw Error('Injected crypto failure')}});await control.locator('#pow-step').click();await control.waitForFunction(()=>!document.querySelector('#pow-step').disabled);assert.match(await control.locator('#pow-mining-sim [role=status]').textContent(),/Injected crypto failure/);await control.close();
 const p=await b.newPage({javaScriptEnabled:false,viewport:{width:390,height:1000}});await route(p);await p.goto(preview+'ds/DS-C4.html');for(const id of ['ds-ledger-fork','ds-pow-trial'])assert(await p.locator(`[data-static-diagram="${id}"] img`).isVisible());for(const s of ['[data-ledger-trace]','[data-pow-trace]']){await p.locator(s+' summary').click();assert(await p.locator(s+' table').isVisible())}assert.equal(await p.locator('[data-ledger-block]').count(),6);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.close();fs.writeFileSync(path.join(out,'ledger-test.json'),JSON.stringify({trials,examples,results,noJavaScript:true,injectedControls:{trialLimit:50000,cryptoFailure:true}},null,2));console.log('Desktop/mobile: all fork arrivals and branch inspection; real hashes, 5-block batch, stop/reset race, difficulty, keyboard scrolling and no-JS figures/traces; injected batch limit and crypto failure passed');
 }finally{await b.close()}
}
main().catch(e=>{console.error(e);process.exitCode=1});
