const model=require('../../cybersecurity/assets/policy-model.cjs'),font=require('./font.cjs'),{palette:p}=require('./render.cjs');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function render(options){const rows=model.examples(options),width=740,height=410,x=t=>240+140*t,y=i=>100+110*i;
const text=(x,y,s,color=p.ink,anchor='start')=>`<text x="${x}" y="${y}" fill="${color}" text-anchor="${anchor}">${esc(s)}</text>`;
let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" style="background:${p.paper};font-family:'IBM Plex Mono',monospace;font-size:14px"><title>Observation attacks: changed trajectories need separate return evaluation</title><metadata>${esc(font.license)}</metadata><style data-embedded-font="${font.sha256}">${font.css}</style><defs><marker id="policy-arrow" viewBox="0 0 8 8" refX="8" refY="4" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L8 4L0 8Z" fill="${p.cobalt}"/></marker><marker id="policy-arrow-red" viewBox="0 0 8 8" refX="8" refY="4" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L8 4L0 8Z" fill="${p.accent}"/></marker></defs>`;
svg+=text(16,26,'Same first-step attack · different time limits');for(let t=0;t<4;t++)svg+=text(x(t),58,'t='+t,p.ink,'middle');
rows.forEach((r,i)=>{const cy=y(i);svg+=`<g data-trace="${r.id}">`+text(16,cy,r.label)+text(16,cy+24,'G='+r.total.toFixed(2));const states=[r.trace[0].s,...r.trace.map(s=>s.next)];states.forEach((s,t)=>{svg+=`<circle data-state="${t}" data-value="${s}" cx="${x(t)}" cy="${cy}" r="19" fill="${p.panel}" stroke="${p.cobalt}" stroke-width="1.5"/>`+text(x(t),cy+5,s,p.ink,'middle');});r.trace.forEach(step=>{const changed=model.action(step.o)!==step.a,color=changed?p.accent:p.cobalt;svg+=`<path data-step="${step.t}" data-action="${step.a}" data-reward="${step.reward}" d="M${x(step.t)+19} ${cy}H${x(step.t+1)-20}" stroke="${color}" stroke-width="1.5" fill="none" marker-end="url(#policy-arrow${changed?'-red':''})"/>`+text((x(step.t)+x(step.t+1))/2,cy-15,step.a+' · r='+step.reward,color,'middle');});const first=r.trace[0];svg+=text(x(0),cy+43,`o: ${first.o.toFixed(2)} → ${first.seen.toFixed(2)}`,first.delta?p.accent:p.ink,'middle')+text(x(states.length-1),cy+43,r.terminal?'terminal':'time limit',p.ink,'middle')+'</g>';});
svg+=text(16,height-12,'Circles: true states · arrows: actions and rewards · γ='+rows[0].gamma);return {svg:svg+'</svg>\n',width,height,rows,x,y};}
module.exports={render,model};
