const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process'),m=require('../../cybersecurity/assets/policy-model.cjs');
const close=(a,b)=>assert(Math.abs(a-b)<1e-8,`${a} != ${b}`);let gradients=0,rollouts=0,budgets=0,invalid=0;
for(let i=1;i<100;i++){const o=i/100;for(const y of [0,1]){const h=1e-6,g=(m.loss(o+h,y)-m.loss(o-h,y))/(2*h);close(g,4*(m.probability(o)-y));gradients++;}}
for(let i=0;i<=100;i++)for(const epsilon of [0,.01,.1,.25,.4,.75,1]){const o=i/100,r=m.perturb(o,epsilon);assert(r.q>=0&&r.q<=1);assert(Math.abs(r.delta)<=epsilon+1e-12);close(r.delta,r.q-o);assert(m.loss(r.q,r.reference)>=m.loss(o,r.reference)-1e-12);budgets++;}
const transitions={'0L':0,'0R':1,'1L':0,'1R':2};for(const [key,next] of Object.entries(transitions))assert.deepEqual(m.step(Number(key[0]),key[1]),{next,reward:next===2?1:0,terminal:next===2});
for(const horizon of [1,2,3,4,5,6,7,8])for(const epsilon of [0,.1,.25,.250001,.4,.75,1])for(const gamma of [0,.25,.5,.9,1]){const r=m.rollout({horizon,epsilon,gamma}),flipped=epsilon>.25,actions=(flipped?['L','R','R']:['R']).slice(0,horizon);assert.deepEqual(r.trace.map(t=>t.a),actions);let s=1,total=0;for(const [t,a] of actions.entries()){const next=transitions[s+a],reward=next===2?1:0;assert.equal(r.trace[t].s,s);assert.equal(r.trace[t].o,(s+2)/4);assert.equal(r.trace[t].next,next);assert.equal(r.trace[t].reward,reward);if(t>0)assert.equal(r.trace[t].seen,r.trace[t].o);total+=gamma**t*reward;s=next;}assert.equal(r.finalState,s);assert.equal(r.terminal,s===2);close(r.total,total);close(r.total,flipped?(horizon<3?0:gamma**2):1);rollouts++;}
assert.equal(m.action(.5),'R');assert.equal(m.perturb(.75,1).q,0);assert.deepEqual(m.examples().map(r=>r.total),[1,0,1]);close(m.examples({gamma:.9})[2].total,.81);
for(const fn of [()=>m.step(2,'R'),()=>m.step(1,'bad'),()=>m.observation(-1),()=>m.observation(.5),()=>m.probability(NaN),()=>m.probability(2),()=>m.loss(.5,2),()=>m.perturb(.5,-1),()=>m.perturb(.5,Infinity),()=>m.rollout({horizon:0}),()=>m.rollout({horizon:9}),()=>m.rollout({gamma:-1}),()=>m.rollout({gamma:NaN}),()=>m.rollout({eps:.1}),()=>m.rollout(null),()=>m.rollout([]),()=>m.examples({horizon:2})]){assert.throws(fn);invalid++;}
const options={epsilon:.4,gamma:.9},before=JSON.stringify(options);m.examples(options);assert.equal(JSON.stringify(options),before);
const file=process.env.NOTES_HUANG_PDF;assert(file,'Provide reviewed Huang v1 PDF');const sha=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');assert.equal(sha,'020f43c7a196e1ea9bb967ea48b5a1010f99e616f0df041a64391b03edf228d7');const source=execFileSync('pdftotext',['-raw',file,'-'],{encoding:'utf8',maxBuffer:4e6}).replace(/\s+/g,' ');assert.match(source,/softmax of the computed Q-values \(with a temperature of 1\)/);assert.match(source,/average return is taken across ten trajectories/);assert.match(source,/Chopper Command, Pong, Seaquest, and Space Invaders/);
fs.writeFileSync('/home/ybc/notes-legacy-review-artifacts/policy-test.json',JSON.stringify({gradients,budgets,rollouts,invalid,sourceSha256:sha,examples:m.examples(),scope:'Finite corridor and gradient checks; not policy training or an Atari experiment'},null,2)+'\n');console.log(`${gradients} finite-difference gradients, ${budgets} budgets, ${rollouts} independent rollouts, ${invalid} invalid inputs and pinned source checks passed`);
