const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),plot=require('./policy-plot.cjs');
const root=path.resolve(__dirname,'../..'),asset=root+'/cybersecurity/assets/diagrams/cyber-policy-trajectories.svg',entries=require('./transfer-sources.cjs');
function content(){const r=plot.render();return `<!-- BEGIN POLICY OBSERVATIONS -->
<h3 id="policy-observations">FGSM against a policy: observation, action and return</h3>
<p>One FGSM step uses a gradient of a chosen loss with respect to the input, followed by a constrained input update. Its cost depends on the model and access available; “one gradient” does not mean universally cheap or a one-gradient black-box attack. A surrogate policy may first have to be trained. The policy parameters stay fixed during the input attack.</p>
<p><a href="https://arxiv.org/pdf/1702.02284v1">Huang et al. (2017), §§4–5</a> tested trained DQN, TRPO and A3C policies on four Atari games. They perturbed observations at inference time and measured trajectory returns. Their attack loss opposes the clean policy’s highest-weighted action, which is a reference choice—not an oracle for the truly optimal action. For DQN they differentiated a softmax over Q-values while execution still chose the maximal-Q action.</p>
<pre tabindex="0" role="region" aria-label="Observation attack and environment transition"><code>o_t = observe(s_t)
a_ref = argmax_a π(a | o_t)             # freeze this reference
J(o) = -log π(a_ref | o)
o_seen = clip(o_t + ε sign(gradient_o J), input bounds)
a_t = select_action(policy, o_seen)
s_(t+1), r_(t+1) = environment_step(s_t, a_t)
G = sum_t γ^t r_(t+1)</code></pre>
<p>The attack changes what the agent sees, not the current environment state or reward directly. A changed action can change later states and observations; evaluate the resulting rollout. A local cross-entropy step is not generally the perturbation that minimizes cumulative return. White-box gradients and transfer from a separately trained policy are different access settings; success in those experiments is not a universal guarantee for all policies.</p>
<h4>A runnable counterexample: changed action does not always lower return</h4>
<p>The following corridor is invented for teaching, not a trained network or a recreation of Atari. States are 0, 1 and terminal goal 2; start at 1. L/R moves one cell, clamped to the corridor. Entering 2 gives reward 1 and ends the episode; all other rewards are 0. The observation is o=(s+2)/4. The hand-defined policy has p(R|o)=sigmoid(4(o−0.5)) and executes R when p≥0.5 (including ties), otherwise L.</p>
<p>Attack only the first observation with ε=0.4, clipped to [0,1]. For clean reference R, the gradient is 4(p(R|o)−1), so o=0.75 becomes 0.35. The true state is still 1 until the chosen L action moves it to 0. Later observations are clean. Use γ=1; changing the time limit H changes the evaluated outcome.</p>
<figure data-static-plot="cyber-policy-trajectories" style="max-width:100%;margin:1.6rem 0"><div role="region" tabindex="0" aria-label="Policy trajectories: scroll horizontally" style="max-width:100%;overflow-x:auto;background:#F3EFE3;border:1px solid #C9C3B6;padding:12px;box-sizing:border-box"><img src="../cybersecurity/assets/diagrams/cyber-policy-trajectories.svg" width="${r.width}" height="${r.height}" alt="Clean reaches goal immediately; attacked with two steps runs out of time, while three steps allow recovery to the same goal reward." style="display:block;width:${r.width}px;max-width:none;height:auto;margin:auto"></div><figcaption>All states, action arrows, rewards and totals are computed by the same model. Red marks an action changed from the policy’s clean-observation choice. The attack modifies only the observation at t=0. Terminal trajectories stop: missing later circles are intentional, not missing transitions.</figcaption></figure>
<div role="region" tabindex="0" aria-label="Policy rollout results: scroll horizontally" style="max-width:100%;overflow-x:auto"><table data-policy-results style="min-width:560px"><caption>Exact deterministic corridor runs, γ=1; no empirical policy benchmark</caption><thead><tr><th scope="col">Run</th><th scope="col">Actions</th><th scope="col">Rewards</th><th scope="col">Return G</th><th scope="col">End</th></tr></thead><tbody>
${r.rows.map(row=>`<tr><th scope="row">${row.label}</th><td>${row.trace.map(s=>s.a).join(', ')}</td><td>${row.trace.map(s=>s.reward).join(', ')}</td><td>${row.total.toFixed(2)}</td><td>${row.terminal?'terminal':'time limit'}</td></tr>`).join('\n')}
</tbody></table></div>
<p>The H=3 attacked run recovers the same undiscounted return despite its wrong-way first action. With γ&lt;1, its delayed reward instead gives G=γ², versus clean G=1. Neither action-change rate nor episode length alone determines return. <a href="../cybersecurity/assets/policy-model.cjs" download>Download the corridor, attack and rollout model</a>. The example has no training loop and supplies no claim about Atari scores or human imperceptibility.</p>
<details data-policy-check><summary>Does differentiating the attack loss change the policy’s weights?</summary><p>No. This inference-time attack differentiates with respect to the observation, holding weights and the clean reference action fixed. The environment then evolves through the executed action. Retraining the policy or directly modifying rewards would be different operations.</p></details>
<!-- END POLICY OBSERVATIONS -->`;}
function next(e,html){const re=/<!-- BEGIN POLICY OBSERVATIONS -->[\s\S]*?<!-- END POLICY OBSERVATIONS -->|<p><strong>Computational cost[\s\S]*?<\/p>/;assert(re.test(html));return html.replace(re,content());}
if(require.main===module){const r=plot.render(),check=process.argv.includes('--check');if(check)assert.equal(fs.readFileSync(asset,'utf8'),r.svg);else fs.writeFileSync(asset,r.svg);let patch='*** Begin Patch\n';for(const e of entries){const file=root+'/'+e.file,old=fs.readFileSync(file,'utf8'),s=next(e,old);if(check)assert.equal(old,s,e.file+' policy drift');else if(old!==s)patch+='*** Update File: '+file+'\n'+require('./transfer-content.cjs').hunks(old,s);}if(check)console.log('Policy trajectories, model-derived tables and both chapter explanations in sync');else process.stdout.write(patch+'*** End Patch\n');}
module.exports={next,content,plot,asset};
