const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),data=require('./privacy-sources.cjs'),{createRenderer,palette}=require('./render.cjs');
const asset=root+'/cybersecurity/assets/diagrams/'+data.diagram.id+'.svg';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function table(attr,caption,heads,rows){return `<div role="region" tabindex="0" aria-label="${esc(caption)}: scroll horizontally" style="max-width:100%;overflow-x:auto"><table ${attr} style="min-width:700px;table-layout:fixed;width:100%"><caption>${esc(caption)}</caption><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>\n${rows.join('\n')}\n</tbody></table></div>`;}
function taxonomy(){return `<p>Separate <strong>the information targeted</strong> from <strong>when and how the attack is executed</strong>. Attacks on training-data privacy can query an already-trained model. They are not training-time interventions such as poisoning.</p>
<p>The slides group membership inference, inversion and extraction under “training-time threats.” Read that as a shorthand for their connection to training data, not as an execution timeline. The six entries below describe different questions and mechanisms, not six mutually exclusive or automatically successful attacks.</p>
${table('data-privacy-threats','Privacy questions, access and evidence limits',['Threat / target','Access or illustrative scenario','What must not be inferred'],data.threats.map(t=>`<tr data-threat="${t.id}"><th scope="row">${esc(t.name)}<br><span style="font-weight:400">${esc(t.target)}</span></th><td>${esc(t.access)}${t.ref?` <a href="${data.sources[t.ref]}">Primary study</a>`:''}</td><td>${esc(t.limit)}</td></tr>`))}
<p>Confidentiality concerns unauthorized learning or disclosure. Prompt injection instead describes an instruction-manipulation mechanism whose intended consequences can include confidentiality, integrity or availability losses. Determine which consequences occurred in the actual application; an attack name alone is not outcome evidence.</p>
<details data-privacy-taxonomy-check><summary>Is querying a deployed model to infer training-set membership a training-time attack?</summary><p>No: the target information concerns training, but this attack is executed against a trained model. Unlike poisoning, it need not modify training data or parameters. Keep target, access, timing and observed success separate.</p></details>`;}
function memory(r){const d=data.diagram;return `<div id="privacy-provenance">
<p>Learning useful statistical structure is not the same as verbatim memorization. Also distinguish information retained in parameters from information supplied in a live session. A system can disclose a newly retrieved record without having trained on it.</p>
<figure data-static-diagram="${d.id}" data-privacy-diagram style="max-width:100%;margin:1.6rem 0"><div role="region" tabindex="0" aria-label="Training and context information paths: scroll horizontally" style="max-width:100%;overflow-x:auto;background:${palette.paper};border:1px solid ${palette.rule};padding:12px;box-sizing:border-box"><img src="../cybersecurity/assets/diagrams/${d.id}.svg" width="${r.width}" height="${r.height}" alt="Training produces weights; weights and live context independently feed generation, followed by an authorization assessment of the output." style="display:block;width:${r.width}px;max-width:none;height:auto;margin:auto"></div><figcaption>${esc(d.caption)}</figcaption></figure>
<h3>Define what the measurement counts</h3>
<p>In Carlini et al., Definition 3.1, extractability means a training sequence can be split into a k-token prefix p and suffix s, with greedy generation from p reproducing s exactly. This is an operational test, not a complete measure of everything learned. Their evaluation uses withheld 50-token suffixes; prompt length and the sample’s duplication distribution matter. See <a href="${data.sources.quantifying}#S3">methodology</a>.</p>
<p>The paper reports log-linear trends with size, duplication and context in its evaluated settings, with qualifications across model families. It does not establish a universal super-linear law. The slides’ 1.3B / 6.7B / 175B table lacks a verified matching result and denominator in the cited paper; it is removed here rather than presented as measured data. See <a href="${data.sources.quantifying}#S4">experiments</a> and <a href="${data.sources.quantifying}#S5">replication study</a>. No experiment is rerun in this figure.</p>
${table('data-privacy-cases','Four illustrative evidence checks — not measured model outputs',['Observation / setup','What it supports','What it does not establish'],data.cases.map(c=>`<tr data-case="${c.id}"><th scope="row" style="font-weight:400">${esc(c.setup)}</th><td>${esc(c.conclusion)}</td><td>${esc(c.limit)}</td></tr>`))}
<details data-privacy-memory-check><summary>A newly retrieved confidential string appears in a web-search query. Does that prove training-data memorization?</summary><p>No. The live-context path is sufficient in this example; no weight update is needed. Inspect the trace and the recipient’s authorization. If the same string was also in training, this trace alone still cannot attribute its production uniquely to one path.</p></details>
</div>`;}
const quiz=`<summary>Distinguish training-data privacy attacks from live-context threats. Must the former execute during training?</summary>
<p>No. Membership inference asks whether a candidate was in training; inversion estimates unknown features or representations; extraction seeks particular training content. These can attack an already-trained model. Runtime context can also leak directly or enable inference from released fragments, without training on the secret. Prompt injection is an attempted instruction manipulation, not a guaranteed privacy breach. State target, access, timing and measured outcome separately.</p>`;
function next(e,html,r){let s=html;const reworked=e.file.startsWith('cybersecurity-reworked/');
if(reworked){const re=/<section id="s10">[\s\S]*?(?=<h3>What counts as a loss: PII vs sensitive information<\/h3>)/;assert(re.test(s));s=s.replace(re,`<section id="s10">\n<h2>10. Privacy surface: weights, context and evidence</h2>\n${memory(r)}\n`);}
else {const re=/<section id="s12">[\s\S]*?(?=<h3>From Statistical NLP to Large Language Models<\/h3>)/;assert(re.test(s));s=s.replace(re,`<section id="s12">\n<h2>12. Memorization and the Privacy Surface</h2>\n${memory(r)}\n`);}
const tax=/<section id="s11">[\s\S]*?<\/section>/;assert(tax.test(s));s=s.replace(tax,`<section id="s11">\n<h2>11. Privacy threats: target, access and timing</h2>\n${taxonomy()}\n</section>`);
const q=/<summary>(?:List three training-time and three inference-time privacy threats for LLMs\.|Distinguish training-data privacy attacks from live-context threats\. Must the former execute during training\?)<\/summary>\s*<p>[\s\S]*?<\/p>/;assert(q.test(s));s=s.replace(q,quiz);
if(reworked)s=s.replace(/(<a href="#s10">)[^<]*(<\/a>)/,'$1Privacy surface: weights, context and evidence$2').replace('<p><strong>Motivation.</strong> If we cannot un-memorize the training data, perhaps the model can be <em>instructed</em> to keep secrets at runtime. That hope rests on two capabilities — in-context learning and alignment — so define them precisely before testing whether they hold.</p>','<p><strong>Motivation.</strong> Can runtime instructions help protect confidential context? This question is distinct from preventing training-data extraction. In-context learning and alignment may influence behavior, but neither is an enforced access-control boundary.</p>');
return s.replace(/(<a href="#s11">)[^<]*(<\/a>)/,'$1Privacy threats: target, access and timing$2');}
function dimensions(){const s=fs.readFileSync(asset,'utf8');return {width:Number(s.match(/\bwidth="([\d.]+)"/)[1]),height:Number(s.match(/\bheight="([\d.]+)"/)[1])};}
if(require.main===module)(async()=>{const renderer=await createRenderer();let r;try{r=await renderer.render(data.diagram);if(process.argv.includes('--check'))assert.equal(fs.readFileSync(asset,'utf8'),r.svg+'\n');else fs.writeFileSync(asset,r.svg+'\n');}finally{await renderer.close();}let patch='*** Begin Patch\n';for(const e of require('./transfer-sources.cjs')){const file=root+'/'+e.file,old=fs.readFileSync(file,'utf8'),s=next(e,old,r);if(process.argv.includes('--check'))assert.equal(old,s,e.file+' privacy drift');else if(old!==s)patch+='*** Update File: '+file+'\n'+require('./transfer-content.cjs').hunks(old,s);}if(process.argv.includes('--check'))console.log('Privacy provenance SVG, evidence tables, quiz and TOC in sync');else process.stdout.write(patch+'*** End Patch\n');})().catch(e=>{console.error(e);process.exitCode=1;});
module.exports={data,asset,dimensions,next,memory,taxonomy};
