const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process'),c=require('./privacy-content.cjs');
const dir=process.env.NOTES_PRIVACY_EVIDENCE;assert(dir,'Set NOTES_PRIVACY_EVIDENCE to the reviewed PDF directory');
const pins={quantifying:'0576532d261e96053ab5d654542f466c80c123c7768c4a082bcaf93d837fff5e',membership:'1891b19eb63ab3caad78d23d610b78a6698927959421e316996c0d1d48fddaaf',inversion:'8be1f2fcf15dee1f3469b06a4f4a083f0c93b2eb37289c8c39dd43d85ad12649'};
const evidence={};for(const [name,sha] of Object.entries(pins)){const file=path.join(dir,name+'.pdf');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),sha);evidence[name]=execFileSync('pdftotext',['-raw',file,'-'],{encoding:'utf8',maxBuffer:5e6}).replace(/\s+/g,' ');}
assert.match(evidence.quantifying,/Definition 3.1./);assert.match(evidence.quantifying,/produces s when prompted with p using greedy decoding/);assert.match(evidence.quantifying,/three log-linear relationships/);assert.match(evidence.quantifying,/next 50 token suffix/);
assert.match(evidence.membership,/inputs drawn from the same population but not used during the training/);assert.match(evidence.membership,/nor, given a record, does it infer whether this record was in the training dataset/);
assert.match(evidence.inversion,/exploits confidence values revealed along with predictions/);assert.match(evidence.inversion,/black-box access to prediction models/);
assert.equal(c.data.threats.length,6);assert.equal(c.data.cases.length,4);for(const t of c.data.threats){assert(t.target&&t.access&&t.limit);if(t.ref)assert(c.data.sources[t.ref].startsWith('https://'));}
assert.match(c.data.threats[0].limit,/non-member does not mean out-of-distribution/);assert.match(c.data.threats[1].limit,/need not be an exact stored photograph/);assert.match(c.data.cases[1].limit,/Not evidence/);assert.match(c.data.cases[3].limit,/Not proof/);
(async()=>{const {parse}=await import('../contracts/node_modules/parse5/dist/index.js'),root=path.resolve(__dirname,'../..');
for(const e of require('./transfer-sources.cjs')){const html=fs.readFileSync(root+'/'+e.file,'utf8');assert.equal(c.next(e,html,c.dimensions()),html);const errors=[];parse(html,{onParseError:e=>errors.push(e)});assert.deepEqual(errors,[]);
 for(const wrong of ['~100,000+','~10,000','root cause of most privacy leakage','Reconstructing training samples from model weights','Training-time threats are static','List three training-time and three inference-time privacy threats'])assert(!html.includes(wrong),wrong);
 const old=execFileSync('git',['show','3695497:'+e.file],{cwd:root,encoding:'utf8'});for(const marker of ['data-kit="tabs"','data-kit="state-explorer"','data-fgsm'])assert.equal(html.split(marker).length,old.split(marker).length,'Preserve '+marker);
 const scripts=s=>[...s.matchAll(/<script\b[^>]*\bsrc="([^"]+)"/g)].map(m=>m[1]).sort();assert.deepEqual(scripts(html),[...scripts(old),'../cybersecurity/assets/agent-policy-model.js','../cybersecurity/assets/agent-policy-widget.js'].sort());assert.equal(html.split('<script').length,old.split('<script').length+2,'Only two intentional agent script additions');
}
fs.writeFileSync('/home/ybc/notes-legacy-review-artifacts/privacy-test.json',JSON.stringify({pins,threats:6,cases:4,markup:true,idempotence:true,scope:'Source and content checks; illustrative cases are not measured model outputs'},null,2)+'\n');console.log('Three pinned source PDFs, six threat distinctions, four evidence cases, markup, preserved widget hooks and generator sync passed');})().catch(e=>{console.error(e);process.exitCode=1;});
