// Course content only. All positions, sizes and routes are calculated by presets.
const field=(name,key)=>({name,...key?{key}:{}});
const tables=[
 {id:'vendite',name:'Vendite',fields:[field('ID_Settimane','PK/FK'),field('ID_Prodotti','PK/FK'),field('ID_Negozi','PK/FK'),field('Quantità'),field('Guadagno')]},
 {id:'settimane',name:'Settimane',fields:[field('ID_Settimane','PK'),field('Settimana'),field('Mese')]},
 {id:'prodotti',name:'Prodotti',fields:[field('ID_Prodotti','PK'),field('Prodotto'),field('Tipo'),field('Categoria'),field('Fornitore')]},
 {id:'negozi',name:'Negozi',fields:[field('ID_Negozi','PK'),field('Negozio'),field('Città'),field('Stato'),field('Rappresentante')]}
];
const references=['Settimane','Prodotti','Negozi'].map(name=>({from:'vendite',field:'ID_'+name,to:name.toLowerCase(),target:'ID_'+name}));
const snow=structuredClone(tables);
snow[2].fields=[field('ID_Prodotti','PK'),field('Prodotto'),field('ID_Tipo','FK'),field('Fornitore')];
snow[3].fields=[field('ID_Negozi','PK'),field('Negozio'),field('ID_Città','FK'),field('Rappresentante')];
snow.push({id:'tipi',name:'Tipi',fields:[field('ID_Tipo','PK'),field('Tipo'),field('Categoria')]},{id:'citta',name:'Città',fields:[field('ID_Città','PK'),field('Città'),field('Stato')]});
module.exports=[
 {file:'irs/cap-08-behavior-trees.html',prefix:'Plate',spec:{preset:'behavior-tree',id:'irs-8-1',plate:'8.1',title:'Find, pick and place: an ordered behavior tree',tree:{id:'root',kind:'root',children:[{id:'sequence',kind:'sequence',children:[{id:'find',kind:'action',label:'find ball'},{id:'pick',kind:'action',label:'pick ball'},{id:'place',kind:'action',label:'place ball'}]}]}},caption:'The find-pick-place example from the slides. The root generates ticks; the Sequence (→) visits children from left to right, advancing only after SUCCESS. FAILURE or RUNNING stops the current traversal. Rectangles are actions; execution leaves can also be conditions. The tree specifies the task; a reusable tick engine executes it.'},
 {file:'irs/cap-08-behavior-trees.html',prefix:'Plate',spec:{preset:'behavior-tree',id:'irs-8-4',plate:'8.4',title:'Prioritized robot behaviors with explicit activation conditions',tree:{id:'fallback',kind:'fallback',children:[{id:'avoid-sequence',kind:'sequence',children:[{id:'obstacle',kind:'condition',label:'obstacle condition'},{id:'avoid',kind:'action',label:'avoid obstacle'}]},{id:'photo-sequence',kind:'sequence',children:[{id:'light',kind:'condition',label:'phototaxis condition'},{id:'photo',kind:'action',label:'phototaxis'}]},{id:'random',kind:'action',label:'random walk'}]}},caption:'The variant: activation conditions are lifted out of the behaviors. The Fallback (?) tries branches in priority order, left to right; each Sequence (→) checks its condition before ticking its action. Ellipses are conditions, rectangles are actions. A RUNNING action retains control; a failed condition lets the Fallback try the next branch. As in section 5, the nonterminating controller actions do not return SUCCESS. This favors reuse, but coherence between each condition and behavior remains the author’s responsibility.'},
 {file:'bi/cap-11-progettazione-logica.html',prefix:'Tavola',spec:{preset:'relational-schema',id:'bi-11-3',plate:'11.3',title:'Schema a stella delle vendite con join fra chiavi esterne e primarie',root:'vendite',tables,references},caption:'Lo schema a stella delle vendite, disposto per rendere leggibili i join: la fact table Vendite importa le tre chiavi delle dimension table. Ogni freccia FK → PK rappresenta una relazione molti-a-uno (N:1), non un flusso di dati. In questo schema le tre chiavi esterne costituiscono insieme la chiave primaria della fact table (PK/FK); Quantità e Guadagno sono misure. Le dimensioni contengono le gerarchie denormalizzate. Le chiavi surrogate sono identificatori generati dal sistema, senza significato applicativo.'},
 {file:'bi/cap-11-progettazione-logica.html',prefix:'Tavola',spec:{preset:'relational-schema',id:'bi-11-4',plate:'11.4',title:'Snowflake delle vendite: Tipi dipende da Prodotti e Città da Negozi',root:'vendite',tables:snow,references:[...references,{from:'prodotti',field:'ID_Tipo',to:'tipi',target:'ID_Tipo'},{from:'negozi',field:'ID_Città',to:'citta',target:'ID_Città'}]},caption:'Lo snowflake schema delle vendite. La fact table resta identica e importa solo le chiavi delle dimension table primarie: Settimane, Prodotti e Negozi. Prodotti importa ID_Tipo da Tipi; Negozi importa ID_Città da Città. Tipi e Città non si collegano direttamente a Vendite: raggiungerne gli attributi richiede il join attraverso la rispettiva dimensione primaria. Le frecce collegano esattamente FK e PK (N:1); PK/FK indica una componente della chiave primaria composta.'},
 {file:'reti-lm/cap-10-tcp-connessione.html',prefix:'Tavola',spec:{preset:'sequence',id:'reti-lm-10-2',plate:'10.2',title:'Three-Way Handshake TCP: SYN, SYN+ACK, ACK e numeri di sequenza',participants:[{id:'a',label:'host A'},{id:'b',label:'host B'}],messages:[{from:'a',to:'b',label:'SYN=1 · ACK=0',detail:'SeqN=x'},{from:'b',to:'a',label:'SYN=1 · ACK=1',detail:'SeqN=y · AckN=x+1',accent:true},{from:'a',to:'b',label:'SYN=0 · ACK=1',detail:'SeqN=x+1 · AckN=y+1'}]},caption:'Il Three-Way Handshake. Il tempo scorre verso il basso su entrambe le linee; la spaziatura è schematica, non una misura del ritardo. Il secondo segmento conferma il numero di A e propone quello di B; il terzo prova a B che anche il suo numero iniziale è stato ricevuto. SYN occupa una posizione nello spazio di sequenza: i primi dati partono da x+1 e y+1. Un ACK senza dati né SYN/FIN non consuma numeri di sequenza.'}
];
